#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch






import base64, codecs
magic = 'aW1wb3J0IHRpbWUKaW1wb3J0IHVybGxpYi5yZXF1ZXN0CmltcG9ydCByYW5kb20KdmVyID0gKCdcMDMzWzE7OTZtVmVyc8OjbyBcMDMzWzE7OTdtWyBcMDMzWzE7OTZtMS4wLjIgXDAzM1sxOzk3bV0gXDAzM1swOzBtJykKCgpjcmlwdG9ncmFmaWEgPSAoJycnClwwMzNbMTs5N20gICBfX18gICAgIF8gICAgICAgXyAgICAgICAgICAgICAgICAgICBcMDMzWzE7OTZtICAgICAgX18gXyAgICAgICAKXDAzM1sxOzk3bSAgLyBfX1wgX18oXylfIF9fIHwgfF8gX19fICBcMDMzWzE7OTZtIF9fIF8gXyBfXyBfXyBfIC8gXyhfKSBfXyBfIApcMDMzWzE7OTdtIC8gLyB8ICdfX3wgfCAnXyBcfCBfXy8gXyBcIFwwMzNbMTs5Nm0vIF9gIHwgJ19fLyBfYCB8IHxffCB8LyBfYCB8ClwwMzNbMTs5N20vIC9fX3wgfCAgfCB8IHxfKSB8IHx8IChfKSBcMDMzWzE7OTZtfCAoX3wgfCB8IHwgKF98IHwgIF98IHwgKF98IHwKXDAzM1sxOzk3bVxfX19fL198ICB8X3wgLl9fLyBcX19cX19fLyBcMDMzWzE7OTZtXF9fLCB8X3wgIFxfXyxffF98IHxffFxfXyxffApcMDMzWzE7OTdtICAgICAgICAgICAgfF98ICAgICAgICAgICAgIFwwMzNbMTs5Nm18X19fLyAKICAgICAgICAgICAgClwwMzNbMTs5N21AXDAzM1sxOzk2bUZhdGFsc2VjIAonJycpCgpjb25zdWx0YW1hYyA9ICgnJycKXDAzM1sxOzk2bSBfXyAgIF9fICAgICAgICBfXyAgICAgICAgICAgIF9fXyAgICAgICAgICBcMDMzWzE7OTZtICAgICAgICAgICAgX18gIApcMDMzWzE7OTZtLyAgYCAvICBcIHxcIHwgL19fYCB8ICB8IHwgICAgIHwgICAvXCAgXDAzM1sxOzk3bV9fICBcMDMzWzE7OTZtIHxcL3wgIC9cICAvICBgIApcMDMzWzE7OTZtXF9fLCBcX18vIHwgXHwgLl9fLyBcX18vIHxfX18gIHwgIC9+flwgICAgIFwwMzNbMTs5Nm0gfCAgfCAvfn5cIFxfXywgCgogXDAzM1sxOzk3bUBcMDMzWzE7OTZtRmF0YWxzZWMgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCicnJykKCmluZWUxID0gICgnJycKClwwMzNbMTs5Nm3ilojilojigIHilojilojilojigIEgICDilojilojigIHilojilojilojilojilojilojilojigIEg4paI4paI4paI4paI4paI4paI4oCBIFwwMzNbMTs5N23ilojilojilojilojilojilojilojigIHilojilojilojilojilojilojilojigIEg4paI4paI4paI4paI4paI4paI4oCBClwwMzNbMTs5Nm3ilojilojigIHilojilojilojilojigIEgIOKWiOKWiOKAgeKWiOKWiOKAgeKAgeKAgeKAgeKAgeKAgeKWiOKWiOKAgeKAgeKAgeKAgeKWiOKWiOKAgVwwMzNbMTs5N23ilojilojigIHigIHigIHigIHigIHigIHilojilojigIHigIHigIHigIHigIHigIHilojilojigIHigIHigIHigIHigIHigIEKXDAzM1sxOzk2beKWiOKWiOKAgeKWiOKWiOKAgeKWiOKWiOKAgSDilojilojigIHilojilojilojilojilojigIEgIOKWiOKWiOKAgSAgIOKWiOKWiOKAgVwwMzNbMTs5N23ilojilojilojilojilojilojilojigIHilojilojilojilojilojigIEgIOKWiOKWiOKAgSAgICAgClwwMzNbMTs5Nm3ilojilojigIHilojilojigIHigIHilojilojigIHilojilojigIHilojilojigIHigIHigIHigIEgIOKWiOKWiOKAgSAgIOKWiOKWiOKAgeKAgVwwMzNbMTs5N23igIHigIHigIHigIHilojilojigIHilojilojigIHigIHigIHigIEgIOKWiOKWiOKAgSAgICAgClwwMzNbMTs5Nm3ilojilojigIHilojilojigIEg4oCB4paI4paI4paI4paI4oCB4paI4paI4oCBICAgICDigIHilojilojilojilojilojilojigIFcMDMzWzE7OTdt4oCB4paI4paI4paI4paI4paI4paI4paI4oCB4paI4paI4paI4paI4paI4paI4paI4oCB4oCB4paI4paI4paI4paI4paI4paI4oCBCgpcMDMzWzE7OTZtQFwwMzNbMTs5N21GQVRBTFNFQ1wwMzNbMDswbeKAgeKAgeKAgeKAgeKAgSAg4oCB4oCB4oCB4oCB4oCB4oCB4oCB4oCBICAgICAg4oCB4oCB4oCB4oCB4oCB4oCB4oCBIOKAgeKAgeKAgeKAgeKAgeKAgeKAgeKAgeKAgeKAgeKAgeKAgeKAgeKAgeKAgeKAgSDigIHigIHigIHigIHigIHigIHigIEKJycnKQoKaW5lZTIgPSAoJycnCgpcMDMzWzE7OTZt4paI4paI4pWX4paI4paI4paI4pWXICAg4paI4paI4pWX4paI4paI4paI4paI4paI4paI4paI4pWXIOKWiOKWiOKWiOKWiOKWiOKWiOKVlyBcMDMzWzE7OTdt4paI4paI4paI4paI4paI4paI4paI4pWX4paI4paI4paI4paI4paI4paI4paI4pWXIOKWiOKWiOKWiOKWiOKWiOKWiOKVlwpcMDMzWzE7OTZt4paI4paI4pWR4paI4paI4paI4paI4pWXICDilojilojilZHilojilojilZTilZDilZDilZDilZDilZ3ilojilojilZTilZDilZDilZDilojilojilZdcMDMzWzE7OTdt4paI4paI4pWU4pWQ4pWQ4pWQ4pWQ4pWd4paI4paI4pWU4pWQ4pWQ4pWQ4pWQ4pWd4paI4paI4pWU4pWQ4pWQ4pWQ4pWQ4pWdClwwMzNbMTs5Nm3ilojilojilZHilojilojilZTilojilojilZcg4paI4paI4pWR4paI4paI4paI4paI4paI4pWXICDilojilojilZEgICDilojilojilZFcMDMzWzE7OTdt4paI4paI4paI4paI4paI4paI4paI4pWX4paI4paI4paI4paI4paI4pWXICDilojilojilZEgICAgIApcMDMzWzE7OTZt4paI4paI4pWR4paI4paI4pWR4pWa4paI4paI4pWX4paI4paI4pWR4paI4paI4pWU4pWQ4pWQ4pWdICDilojilojilZEgICDilojilojilZFcMDMzWzE7OTdt4pWa4pWQ4pWQ4pWQ4pWQ4paI4paI4pWR4paI4paI4pWU4pWQ4pWQ4pWdICDilojilojilZEgICAgIApcMDMzWzE7OTZt4paI4paI4pWR4paI4paI4pWRIOKVmuKWiOKWiOKWiOKWiOKVkeKWiOKWiOKVkSAgICAg4pWa4paI4paI4paI4paI4paI4paI4pWU4pWdXDAzM1sxOzk3beKWiOKWiOKWiOKWiOKWiOKWiOKWiOKVkeKWiOKWiOKWiOKWiOKWiOKWiOKWiOKVl+KVmuKWiOKWiOKWiOKWiOKWiOKWiOKVlwpcMDMzWzE7OTZt4pWa4pWQ4pWd4pWa4pWQ4pWdICDilZrilZDilZDilZDilZ3ilZrilZDilZ0gICAgICDilZrilZDilZDilZDilZDilZDilZ0gXDAzM1sxOzk3beKVmuKVkOKVkOKVkOKVkOKVkOKVkOKVneKVmuKVkOKVkOKVkOKVkOKVkOKVkOKVnSDilZrilZDilZDilZDilZDilZDilZ0KClwwMzNbMTs5Nm1AXDAzM1sxOzk3bUZBVEFMU0VDXDAzM1swOzBt4oCBICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCicnJykKCgppbmVlMyA9ICgnJycKXDAzM1sxOzk2bSMjIyMgIyMgICAgIyMgIyMjIyMjIyMgICMjIyMjIyMgICBcMDMzWzE7OTdtIyMjIyMjICAjIyMjIyMjIyAgIyMjIyMjICAKXDAzM1sxOzk2bSAjIyAgIyMjICAgIyMgIyMgICAgICAgIyMgICAgICMjIFwwMzNbMTs5N20jIyAgICAjIyAjIyAgICAgICAjIyAgICAjIyAKXDAzM1sxOzk2bSAjIyAgIyMjIyAgIyMgIyMgICAgICAgIyMgICAgICMjIFwwMzNbMTs5N20jIyAgICAgICAjIyAgICAgICAjIyAgICAgICAKXDAzM1sxOzk2bSAjIyAgIyMgIyMgIyMgIyMjIyMjICAgIyMgICAgICMjIFwwMzNbMTs5N20gIyMjIyMjICAjIyMjIyMgICAjIyAgICAgICAKXDAzM1sxOzk2bSAjIyAgIyMgICMjIyMgIyMgICAgICAgIyMgICAgICMjICBcMDMzWzE7OTdtICAgICAjIyAjIyAgICAgICAjIyAgICAgICAKXDAzM1sxOzk2bSAjIyAgIyMgICAjIyMgIyMgICAgICAgIyMgICAgICMjIFwwMzNbMTs5N20jIyAgICAjIyAjIyAgICAgICAjIyAgICAjIyAKXDAzM1sxOzk2bSMjIyMgIyMgICAgIyMgIyMgICAgICAgICMjIyMjIyMgICBcMDMzWzE7OTdtIyMjIyMjICAjIyMjIyMjIyAgIyMjIyMjICAKClwwMzNbMTs5Nm1AXDAzM1sxOzk3bUZBVEFMU0VDXDAzM1swOzBt4oCBIAoKJycnKQoKaW5lZTQgPSAoJycnCgpcMDMzWzE7OTZtZDg4ODg4OGIgZDhiICAgZGIgZDg4ODg4YiAgLmQ4OGIuICAgXDAzM1sxOzk3bS5kODg4OC4gZDg4ODg4YiAgLm84OGIuIApcMDMzWzE7OTZtICBgODgnICAgODg4byAgODggODgnICAgICAuOFAgIFk4LiAgXDAzM1sxOzk3bTg4JyAgWVAgODgnICAgICBkOFAgIFk4IApcMDMzWzE7OTZtICAgODggICAgODhWOG8gODggODhvb28gICA4OCAgICA4OCAgXDAzM1sxOzk3bWA4Ym8uICAgODhvb29vbyA4UCAgICAgIApcMDMzWzE7OTZtICAgODggICAgODggVjhvODggODh+fn4gICA4OCAgICA4OCAgIFwwMzNbMTs5N20gYFk4Yi4gODh+fn5+fiA4YiAgICAgIApcMDMzWzE7OTZtICAuODguICAgODggIFY4ODggODggICAgICBgOGIgIGQ4JyAgXDAzM1sxOzk3bWRiICAgOEQgODguICAgICBZOGIgIGQ4IApcMDMzWzE7OTZtWTg4ODg4OFAgVlAgICBWOFAgWVAgICAgICAgYFk4OFAnICBcMDMzWzE7OTdtIGA4ODg4WScgWTg4ODg4UCAgYFk4OFAnIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApcMDMzWzE7OTZtQFwwMzNbMTs5N21GQVRBTFNFQ1wwMzNbMDswbeKAgSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCicnJykKCgppbmVlNSA9ICgnJycKXDAzM1sxOzk2bSBfX19fXyBfXyAgIF8gX19fX19fXyAgX19fX18gICBcMDMzWzE7OTdtX19fX19fXyBfX19fX19fIF9fX19fX18KXDAzM1sxOzk2bSAgIHwgICB8IFwgIHwgfF9fX19fXyB8ICAgICB8ICBcMDMzWzE7OTdtfF9fX19fXyB8X19fX19fIHwgICAgICAKXDAzM1sxOzk2bSBfX3xfXyB8ICBcX3wgfCAgICAgICB8X19fX198ICBcMDMzWzE7OTdtX19fX19ffCB8X19fX19fIHxfX19fXyAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKXDAzM1sxOzk2bUBcMDMzWzE7OTdtRkFUQUxTRUNcMDMzWzA7MG3igIEKJycnKQoKCmluZWU2ID0gKCcnJwpcMDMzWzE7OTZtICAgICAgICAgICAgICAgICAgICAgICAgLCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgClwwMzNbMTs5Nm0gICAgICAgICAgICAgICAgICAgICAgICAgRXQgICAgICAgICAgIDogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgClwwMzNbMTs5Nm0gICAgICAgTC4gICAgICAgICAgICAgICAgRSN0ICAgICAgICAgdCMsICAgICBcMDMzWzE7OTdtICAgICAgLiAgICAgICAgLDsgICAgICAuLApcMDMzWzE7OTZtICAgdCAgIEVXOiAgICAgICAgLGZ0ICAgIEUjI3QgICAgICAgOyMjVy4gICAgXDAzM1sxOzk3bSAgICAgO1cgICAgICBmI2kgICAgICAsV3QKXDAzM1sxOzk2bSAgIEVqICBFIyM7ICAgICAgIHQjRSAgICBFI1cjdCAgICAgOiNMOldFICAgXDAzM1sxOzk3bSAgICAgZiNFICAgIC5FI3QgICAgICBpI0QuClwwMzNbMTs5Nm0gICBFIywgRSMjI3QgICAgICB0I0UgICAgRSN0ZkwuICAgLktHICAsI0QgXDAzM1sxOzk3bSAgICAuRSNmICAgIGkjVywgICAgICBmI2YgIApcMDMzWzE7OTZtICAgRSN0IEUjZkUjZiAgICAgdCNFICAgIEUjdCAgICAgIEVFICAgIDsjZiBcMDMzWzE7OTdtICBpV1c7ICAgIEwjRC4gICAgIC5EI2kgICAKXDAzM1sxOzk2bSAgIEUjdCBFI3QgRCNHICAgIHQjRSAsZmZXI0RmZmouIGYjLiAgICAgdCNpXDAzM1sxOzk3bSBMIyNMZmZpOksjV2ZmZjsgIDpLVywgICAgClwwMzNbMTs5Nm0gICBFI3QgRSN0ICBmI0UuICB0I0UgIDtMVyNFTExMZi46I0cgICAgIEdLIFwwMzNbMTs5N210TExHIyNMIGkjI1dMTExMdCB0I2YgICAgIApcMDMzWzE7OTZtICAgRSN0IEUjdCAgIHQjSzogdCNFICAgIEUjdCAgICAgIDsjTCAgIExXLiBcMDMzWzE7OTdtICAsVyNpICAgLkUjTCAgICAgIDsjRyAgICAKXDAzM1sxOzk2bSAgIEUjdCBFI3QgICAgOyNXLHQjRSAgICBFI3QgICAgICAgdCNmIGYjOiBcMDMzWzE7OTdtICBqI0UuICAgICAgZiNFOiAgICAgOktFLiAgClwwMzNbMTs5Nm0gICBFI3QgRSN0ICAgICA6SyNEI0UgICAgRSN0ICAgICAgICBmI0QjOyAgXDAzM1sxOzk3bS5EI2ogICAgICAgICAsV1c7ICAgICAuRFc6IApcMDMzWzE7OTZtICAgRSN0IEUjdCAgICAgIC5FIyNFICAgIEUjdCAgICAgICAgIEcjdCAgXDAzM1sxOzk3bSxXSywgICAgICAgICAgIC5EIzsgICAgICBMIywKXDAzM1sxOzk2bSAgIEUjdCAuLiAgICAgICAgIEcjRSAgICBFI3QgICAgICAgICAgdCAgIFwwMzNbMTs5N21FRy4gICAgICAgICAgICAgIHR0ICAgICAgIGp0ClwwMzNbMTs5Nm0gICAsOy4gICAgICAgICAgICAgZkUgICAgOyN0ICAgICAgICAgICAgIFwwMzNbMTs5N20gLCAgICAgICAgICAgICAgICAgICAgICAgICAgIApcMDMzWzE7OTZtICAgICAgICAgICAgICAgICAgICAsICAgICA6OyAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKXDAzM1sxOzk2bUBcMDMzWzE7OTdtRkFUQUxTRUNcMDMzWzA7MG3igIEKJycnKQoKaW5lZTcgPSAoJycnICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgClwwMzNbMTs5Nm0gYDdNTUYnYDdNTi4gICBgN01GJ2A3TU0iIiJZTU0gICAuZzgiIjhxLiAgICBcMDMzWzE7OTdtLk0iIiJiZ2QgYDdNTSIiIllNTSAgICAuZzgiIiJiZ2QgClwwMzNbMTs5Nm0gICBNTSAgICBNTU4uICAgIE0gICAgTU0gICAgYDcgLmRQJyAgICBgWU0uIFwwMzNbMTs5N20sTUkgICAgIlkgICBNTSAgICBgNyAgLmRQJyAgICAgYE0gClwwMzNbMTs5Nm0gICBNTSAgICBNIFlNYiAgIE0gICAgTU0gICBkICAgZE0nICAgICAgYE1NIFwwMzNbMTs5N21gTU1iLiAgICAgICBNTSAgIGQgICAgZE0nICAgICAgIGAgClwwMzNbMTs5'
love = 'Az0tVPOAGFNtVPOAVPOtGH4hVR0tVPNtGH0vVx1AVPNtGH0tVPNtVPNtVR1AVSjjZmAoZGf5A20tVTOMGH1BpF4tVPOAGJ1gGH0tVPNtGH0tVPNtVPNtVPNtPyjjZmAoZGf5Az0tVPOAGFNtVPOAVPNtLR1AYx0tVPNtGH0tVPOMVPNtGH0hVPNtVPNtYR1DVSjjZmAoZGf5A20hVPNtVPOtGH0tVPOAGFNtVSxtVPjtGH0hVPNtVPNtVPNtPyjjZmAoZGf5Az0tVPOAGFNtVPOAVPNtVPOMGH0tVPNtGH0tVPNtVPNtLR1vYvNtVPNfMSNaKQNmZ1fkBmx3oFOALvNtVPNtMR0tVPOAGFNtVPNtYR0tLR1vYvNtVPNtYPptPyjjZmAoZGf5Az0tYxcAGHjhYxcAGP4tVPNtJH0tVP5XGH1ZYvNtVPNtVPOtVzWgoJDvWlNtKQNmZ1fkBmx3oFODVyyvoJ1xVvNtYxcAGJ1goJ1AGH0tVPOtVzWgoJ1xWlNtPvNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtPvNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtPyjjZmAoZGf5Az1NKQNmZ1fkBmx3oHMOIRSZH0IQKQNmZ1fjBmOg4bPOWlpaXDbXPzyhMJH4VQ0tXPpaWjcpZQZmJmR7BGMgo29io28to29iolNtVT9io28to29io29io29io28tVT9io29io28tVPOpZQZmJmR7BGqgVT9io29io29iBPOio29io29io29iolNto29io29io284VNcpZQZmJmR7BGMgVQt4BPNtVQt4BQuiVPN4BPNtVQt4BPNtVPN4BPOiBQt4VPNtBQt4olOpZQZmJmR7BGqgBQt4VPNtVPNtVPNtBQt4VPNtVQt4VT84BQttVPNtVQt4VNcpZQZmJmR7BGMgVQt4BPNtVQt4VQt4BT84BPNtVQt4BT9iomttVPN4BQttVPNtVQt4BPNtKQNmZ1fkBmx3oGt4BT9io29iolNtBQt4o29iBPNtVQt4BPNtVPNtVPNtVNcpZQZmJmR7BGMgVQt4BPNtVQt4VPNtBQt4BPNtVQt4BPNtVPNtVPN4BQuiVPNtomt4BPNtKQNmZ1fkBmx3oFNtVPNtVPN4BQttBQt4VPNtVT9iVQt4BT8tVPNtVT9iVNcpZQZmJmR7BGMgomt4BT8tomt4olNtVPN4BPNtomt4BT8tVPNtVPNtVQt4o29iBQttVPOpZQZmJmR7BGqgomt4o29iomt4BPOiBQt4o29iBQt4BPN4BQuio29iBQttVNbtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNXKQNmZ1fkBmx2oHOpZQZmJmR7BGqgExSHDHkGEHApZQZmJmN7ZT0XWlpaXDbXnJ5yMGxtCFNbWlpaPtbtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNXKQNmZ1fkBmx2oGt4VPN4BQuvVPNtVPNtBQttVQt4BQt4BQt4BQt4VPNfLJD4BQt4LzRfVPNtVPOpZQZmJmR7BGqgLJD4BQt4BTWuVPNtBQt4BQt4BQt4BQttVPkuMQt4BQuvLFjtVPNXKQNmZ1fkBmx2oGt4VPN4BQt4LvNtVPNtBQttVQt4VPNtVPNtVPNtVTD4VvptVPNtLPV4LvNtVSjjZmAoZGf5A21xBPVtVPNtVPV4LvNtBQttVPNtVPNtVPNtMQtvWlNtVPOtVwuvVPNXKQNmZ1fkBmx2oGt4VPN4BPOtBTVtVPNtBQttVQt4VPNtVPNtVPNtMQtaVPNtVPNtVPOtBTVtVSjjZmAoZGf5A21MBPjtVPNtVPNtVPNtBQttVPNtVPNtVPOxBPptVPNtVPNtVPNtVPNXKQNmZ1fkBmx2oGt4VPN4BPNtLQuvVPNtBQttVQt4LJSuLJRtVPNtBQttVPNtVPNtVPNtBQttVSjjZmAoZGf5A21tJGuuLJSuLFjtVPNtBQuuLJSuLFNtVPN4BPNtVPNtVPNtVPNtVPNXKQNmZ1fkBmx2oGt4VPN4BPNtVTN4LvNtBQttVQt4VvVvVvVtVPNtBQttVPNtVPNtVPNtBQttVSjjZmAoZGf5A20tVTNvVvVvVwuvYPNtBQtvVvVvVvNtVPN4BPNtVPNtVPNtVPNtVPNXKQNmZ1fkBmx2oGt4VPN4BPNtVPOtBTVtBQttVQt4VPNtVPNtVPNtJGtfVPNtVPNtVPNfBSNtVSjjZmAoZGf5A20tVPNtVPNtVTN4LvNtBQttVPNtVPNtVPOMBPjtVPNtVPNtVPNtVPNXKQNmZ1fkBmx2oGt4VPN4BPNtVPNtLQt4BQttVQt4VPNtVPNtVPNtVSx4LF4tVPNtYzR4HPNtKQNmZ1fkBmx3oFOMBTRtVPNtVTR4HPNtBQttVPNtVPNtVPNtJGuuYvNtVPNhLGuDVPNXKQNmZ1fkBmx2oGt4VPN4BPNtVPNtVTN4BQttVQt4VPNtVPNtVPNtVPOtVyx4BQt4JFVaVPNtKQNmZ1fkBmx3oFNtVyx4BQt4BSNvVPNtBQt4BQt4BQt4BQttVTNvJGt4BQuMVvptVPNXVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtPyjjZmAoZGf5Az1NKQNmZ1fkBmx3oHMOIRSZH0IQKQNmZ1fjBmOgPvpaWlxXPzyhMJHkZPN9VPtaWlpXPyjjZmAoZGf5Az0tYlDxWPDxWPNiWPDtVPNiWPDtYlDxWPDxWPDxVP8xWPDxWPDtVPOpZQZmJmR7BGqgYlDxWPDxWPNtYlDxWPDxWPDxVPNiWPDxWPDxVNcpZQZmJmR7BGMgsS8tVPDxKl98VPDxWPO8VPDxsPNxWS9sK19sYl8xWS9sVPNxWPOpZQZmJmR7BGqgYlDxK18tVPDxsPNxWS9sK19sYlNiWPEsKlNtWPDXKQNmZ1fkBmx2oFNtsPNxWPNtsPNxWPDxsPNxWUjtWPDtVPNtVUjtWPDtVSjtWPEpZQZmJmR7BGqgsPNxWPNtKS9sY3jtWPDtVPNtVPO8VPDxVPOpK18iPyjjZmAoZGf5Az0tVUjtWPDtVUjtWPDtWPDtWPE8VPDxWPDxVPO8VPDxVPO8VPDxKQNmZ1fkBmx3oKjtVPDxWPDxWPO8VPDxWPDxVPNtsPNxWPNtVPNtVNcpZQZmJmR7BGMgVPO8VPDxVPO8VPDxVPNxWPDxsPNxWS9sYlNtsPNxWPNtsPNxWSjjZmAoZGf5A20tKS9sK18tVPDxsPNxWS9sYlNtVUjtWPDtVPNtVPNXKQNmZ1fkBmx2oFNtsPNxWPNtsPNxWSjtVPDxWUjtWPDtVPNtVUjtWPDtVUjtWPEpZQZmJmR7BGqgVP8xWPNtKPNxWUjtWPDtVPNtVPO8VPDxVPNtVPDxPyjjZmAoZGf5Az0tYlDxWPDxWUjtWPDtKPNtWPE8VPDxVPNtVPO8VPNxWPDxWPDiKQNmZ1fkBmx3oKjtVPDxWPDxWP98VPDxWPDxWPDxsPNtWPDxWPDxYjcpZQZmJmR7BGMgsS9sK19sKl98K18iVPOpK18isS9sYlNtVPNtVSksK19sK18iVSjjZmAoZGf5A20tKS9sK19sKl8tsS9sK19sK19sYlOpK19sK19sYlNXPyjjZmAoZGf5Az1NKQNmZ1fkBmx3oHMOIRSZH0IQKQNmZ1fjBmOgPvpaWlxXPzkiM29zo2EuVQ0tpzShMT9gYzAbo2ywMFuonJ5yMGRfVTyhMJHlYPOcozIyZljtnJ5yMGDfVTyhMJH1YPOcozIyAvjtnJ5yMGpfVTyhMJH4YPOcozIyBFjtnJ5yMGRjKFxXL29hp3IfqTSwMKNtCFNtXPpaWjcpZQZmJmR7BGMgVPNtK19sK18tK19sKlNtKlNtVS8tVS9sK19sVS8tVPNtKlOsVPNtK19sK19sKlNtVPNtVPNtVPNtVSjjZmAoZGf5Az0tVS9sK19sVS9sK19sKlOsK19sKlNtPyjjZmAoZGf5Az0tVP8tK19sKl8tK18tKUjtKPO8VUjiVS9sK198VUjtVUjtsPO8VUksKlNtVS9ssP9pVPNtVPNtVPNtKQNmZ1fkBmx2oFNiVS9sK198VPOsK19ssPNtK18tKPNXKQNmZ1fkBmx2oFO8VUjtVPO8VUjtVUjtsPNtKUjtsPNbK19sVUjtsPNtsPO8VUjtVPNtsPO8VPNiVPOpVPOpZQZmJmR7BGqgK19sK19sKQNmZ1fkBmx2oKjtsPNtVPO8VUksKlNtsPO8K18cVUjXKQNmZ1fkBmx2oFO8VUjtVPO8VUjtVUjtsPNhVTNtsSksK18tKUjtsPNtsPO8VUjtVPNtsPO8VP8tY1jtKPOpZQZmJmR7BGqgK19sK19sKQNmZ1fkBmx2oKjtsPNtVPO8VPOsK3jtsPNtK19sYlNXKQNmZ1fkBmx2oFO8VUksK198VUksK3jtsPO8KPNtsS9sK18cVUjtsS9ssPO8VUksK19ssPO8YlOsK19sVSjtVPNtVSjjZmAoZGf5Az0tsPO8K19sK3jtsS9sK198VUjtVPNtVNcpZQZmJmR7BGMgVPOpK19sK19pK19sKl98K3jtKS98K19sK18iVSksK19sY3ksK19sK198Kl9sYlNtVPOpK1jtVPNtKQNmZ1fkBmx2oFNtKS9sK19ssS9sK19sK3kssPNtVPNXPvOpZQZmJmR7BGqgDSjjZmAoZGf5Az1TLKEuoUAyLjbaWlpcPzqypzSgLJyfVQ0tXPpaWjcpZQZmJmR7BGMgVS9sK19sVPOsK19sK19sK19sKlNtK19sVSjjZmAoZGf5A20tVS9sKlNtK19sVPOsK18tVS9sK19sVS8tVPNtVNcpZQZmJmR7BGMgsPNtK18tKUjtVS9sK3jtK19sVSjiVS8tKPOpZQZmJmR7BGqgVUjtVSjiVPO8VP8tKlOpsS8tVPOssPO8VPNtVNcpZQZmJmR7BGMgsPO8VPOpY3jtsS9sVUjtsS8iVP8tY19pVSjtKQNmZ1fkBmx3oKjtYvNtYvO8YlNiK1jtKPO8VUjtsPO8VPNtVNcpZQZmJmR7BGMgsPO8VS9sVUjtVS9ssUjtVPNtY3jtVS8tVUjtKQNmZ1fkBmx3oKjtsSjisPO8sPNtKlNtsPO8VUjtsPO8VPNtVNcpZQZmJmR7BGMgsPO8K1jtKUjtsS9sK3jtsSjtKUjtsPO8VUjtKQNmZ1fkBmx3oKjtsPNtsPO8sPO8VUjtsS98VUkssPO8K19sKjcpZQZmJmR7BGMgVSksK19sY1ksK19sY1kssPOpK1kssPO8Kl8tKQNmZ1fkBmx3oIkssPNtsS8iKS98VUksY1ksK18iKS9sK19sYjbXKQNmZ1fkBmx2oHOpZQZmJmR7BGqgEzS0LJkmMJApZQZmJmN7ZT0XWlpaXDccpTyhMz8tCFNbWlpaPyjjZmAoZGf5Az0tVS9sKlOsK19sVPOpZQZmJmR7BGqgK19sVS8tVPOsVS9sK19sVS9sKlNtPyjjZmAoZGf5Az0tsS8tK3jtVS8tKPOpZQZmJmR7BGqgKlOssPOpVUjtsPNtK19sYlOsVSjtPyjjZmAoZGf5Az0tVUjtsUjtsS8cVPOpZQZmJmR7BGqgsPO8sPNtKUjtsPO8KlO8VUjtsPO8PyjjZmAoZGf5Az0tVUjtsUjtVS9sYlOpZQZmJmR7BGqgsPO8sPO8KPNtsPNtK3k8VUkssPO8PyjjZmAoZGf5Az0tsS9sK3kssPNtVSjjZmAoZGf5A218K19ssS98VSkssS98VPNtKS9sKl8XPtcpZQZmJmR7BGqgDSjjZmAoZGf5Az1TLKEuoUAyL1jjZmAoZQfjoDbaWlpcPaEyoTIcozMiVQ0tVPtaWlpXKQNmZ1fkBmx2oFNtK19sK18tVPNtKlNtVPNtKQNmZ1fkBmx3oFNtK19sVS8tVPOsVS9sK19sVS9sKlNtPyjjZmAoZGf5Az0tsS8tVPOssS9ssPO8VS9sK1jjZmAoZGf5A20tsS8tK3jtKPO8VUjtVS9sKl8tKlOpVNcpZQZmJmR7BGMgVPNtsPO8YlOsVSjtsP8tKlOpVSjjZmAoZGf5A218VUk8VPOpsPO8VUksVUjtsPO8VUjXKQNmZ1fkBmx2oFNtVUjtsPNtK18iVUjtVS9sYlOpZQZmJmR7BGqgsPO8sPO8KPNtsPNtK3k8VUkssPO8PyjjZmAoZGf5Az0tVPO8K3kpK19ssS98KS9sK3kpZQZmJmR7BGqgVS9sK3kssPOpK3kssPNtVSksK18iVNbXKQNmZ1fkBmx2oHOpZQZmJmR7BGqgEzS0LJkmMJZXWlpaXDcwo250LKEiVQ0tVPtaWlpXKQNmZ1fkBmx2orXJvBXJvBXJvBXJvBXJvBXJvBXIylNt4cnV4cnV4cnV4cnV4cnV4cnV4cJKVPQvybwvybwvybwvybwvybwvybwvyMpt4cnV4cnV4cnV4cnV4cnV4cnV4cnV4cnV4cJKVSjjZmAoZGf5A23vybwvybwvybwvybwvybwvybwvyMptKQNmZ1fkBmx2orXJvBXJvBXJvBXJvBXJvBXJvBXJvBXIylQvybwvybwvybwvybwvybwvyMpt4cnV4cnV4cnV4cnV4cnV4cnV4cnV4cnV4cJKVBXJvBXJvBXJvBXJvBXJvBXIylQvybwvybwvyMptVPNtVBXJvBXJvBXJvBXJvBXJvBXJvBXJvBXIy+XJvBXJvBXJvBXJvBXJvBXJvBXJvBXIylQvybwvybwvybwvybwvybwvybwvyMpXKQNmZ1fkBmx2orXJvBXJvBXIyBXIxBXIxBXJvBXJvBXIy+XJvBXJvBXIyBXIxBXIxBXIxBXJvBXJvBXIy+XJvBXJvBXIyBXIxBXIxBXIxBXJvBXJvBXIy+XIzhXIxBXIxBXJvBXJvBXIyBXIxBXIxBXIaIjjZmAoZGf5A23vybwvybwvyMGvyMQvyMQvyMQvybwvybwvyMqpZQZmJmR7BGMg4cnV4cnV4cJH4cJD4cJD4cJD4cJD4cJq4cnV4cnV4cJH4cJD4cJD4cnV4cnV4cJK4cJn4cJD4cJD4cnV4cnV4cJH4cJD4cJD4cJq4cnV4cnV4cJH4cJD4cJD4cnV4cnV4cJK4cnV4cnV4cJEVPNtVPQvybwvybwvyMGvyMQvyMQvyMQvyMQvyM3vybwvybwvyMGvyMQvyMQvyMQvyMQvyM3vybwvybwvyMGvyMQvyMQvyMQvyMQvyM0XKQNmZ1fkBmx2orXJvBXJvBXJvBXJvBXJvBXJvBXIyBXIarXJvBXJvBXIxFNtVBXJvBXJvBXIxrXJvBXJvBXIxFNtVBXJvBXJvBXIxFNtVBXJvBXJvBXIxFNtVSjjZmAoZGf5A23vybwvybwvyMUvybwvybwvyMsvybwvybwvyMSpZQZmJmR7BGMg4cnV4cnV4cnV4cnV4cnV4cJKVPQvybwvybwvybwvybwvybwvybwvybwvyMRtVPQvybwvybwvyMRtVPQvybwvybwvybwvybwvybwvybwvybwvyMUvybwvybwvyMRtVPNtVBXJvBXJvBXJvBXJvBXJvBXJvBXJvBXIy+XJvBXJvBXJvBXJvBXJvBXIylNt4cnV4cnV4cJEVPNtVPNXKQNmZ1fkBmx2orXJvBXJvBXIyBXIxBXIxBXJvBXJvBXIy+XJvBXJvBXIxFNtVBXJvBXJvBXIxrXJvBXJvBXIxFNtVBXJvBXJvBXIxFNtVBXJvBXJvBXIxFNtVSjjZmAoZGf5A23vybwvybwvyMUvybwvybwvyMUvybwvybwvyMSpZQZmJmR7BGMg4cnV4cnV4cJH4cJD4cJD4cJqVPQvybwvybwvyMGvyMQvyMQvybwvybwvyMRtVPQvybwvybwvyMRtVPQvybwvybwvyMGvyMQvyMQvybwvybwvyMUvybwvybwvyMRtVPNtVBXIzhXIxBXIxBXIxBXIxBXJvBXJvBXIxrXJvBXJvBXIyBXIxBXIxBXIaFNt4cnV4cnV4cJEVPNtVPNXKQNmZ1fkBmx2orXJvBXJvBXIxFNt4cnV4cnV4cJE4cJn4cnV4cnV4cnV4cnV4cnV4cnV4cJH4cJq4cJn4cnV4cnV4cnV4cnV4cnV4cnV4cJH4cJqVPNt4cnV4cnV4cJEVPNtKQNmZ1fkBmx3orXIzhXJvBXIxrXJvBXJvBXJvBXJvBXIyBXIaIjjZmAoZGf5Az3vybwvybwvyMRtVPNtVBXJvBXJvBXIxFNt4cnV4cnV4cJEVPNt4cnV4cnV4cJEVPNt4cnV4cnV4cJEVPQvybwvybwvyMUvybwvybwvybwvybwvybwvybwvybwvyMsvybwvybwvybwvybwvybwvybwvybwvyMUvybwvybwvybwvybwvybwvybwvybwvyMsvyMevybwvybwvybwvybwvybwvybwvyMpXKQNmZ1fkBmx2orXIzhXIxBXIaFNt4cJn4cJD4cJqVBXIzhXIxBXIxBXIxBXIxBXI'
god = 'kOKVnSAg4pWa4pWQ4pWQ4pWQ4pWQ4pWQ4pWdICAgIOKVmuKVkOKVnSAgIFwwMzNbMTs5N20g4pWa4pWd4pWa4pWQ4pWQ4pWQ4pWdIFwwMzNbMTs5Nm3ilZrilZDilZ0gICAgIOKVmuKVkOKVnSAg4pWa4pWQ4pWdICAg4pWa4pWQ4pWdICAg4pWa4pWQ4pWdICDilZrilZDilZ3ilZrilZDilZDilZDilZDilZDilZDilZ3ilZrilZDilZDilZDilZDilZDilZDilZ3ilZrilZDilZDilZDilZDilZDilZDilZ0g4pWa4pWQ4pWQ4pWQ4pWQ4pWQ4pWdCgoKClwwMzNbMTs5MW0jQ09OVEFUTyMKClwwMzNbMTs5Nm1QUk9UT05NQUlMOiBcMDMzWzE7OTdtcm9vdGZhdGFsc2VjQHByb3Rvbm1haWwuY2gKClwwMzNbMTs5Nm1HSVRIVUI6IFwwMzNbMTs5N21odHRwczovL2dpdGh1Yi5jb20vRmF0YWxTM0MvCgpcMDMzWzE7OTZtVEVMRUdSQU06IFwwMzNbMTs5N21odHRwczovL3QubWUvZmF0YWxzZWMKXDAzM1swOzBtCicnJykKCnNxbGxvZ289ICgnJycKClwwMzNbMTs5Nm0gX19fX18gIF9fX19fIF8gICAgICAgICAgICAgICAgICAgICAgICAgClwwMzNbMTs5Nm0vICBfX198fCAgXyAgfCB8ICAgICAgICAgICAgICAgICAgICAgICAgClwwMzNbMTs5Nm1cIGAtLS4gfCB8IHwgfCB8ICAgIFwwMzNbMTs5N21fX18gIF9fXyBfXyBfIF8gX18gIApcMDMzWzE7OTZtIGAtLS4gXHwgfCB8IHwgfCAgIFwwMzNbMTs5N20vIF9ffC8gX18vIF9gIHwgJ18gXCAKXDAzM1sxOzk2bS9cX18vIC9cIFwvJyAvIHxfX19cMDMzWzE7OTdtXF9fIFwgKF98IChffCB8IHwgfCB8ClwwMzNbMTs5Nm1cX19fXy8gIFxfL1xfXF9fX19fXDAzM1sxOzk3bS9fX18vXF9fX1xfXyxffF98IHxffAoKXDAzM1sxOzk2bUBcMDMzWzE7OTdtRmF0YWxzZWMKJycnKQoKd2hvaXNsb2dvID0gKCcnJwpcMDMzWzE7OTZtIF8gICAgICAgX19fXyAgICAgICAgIFwwMzNbMTs5N20gXyAgICAgClwwMzNbMTs5Nm18IHwgICAgIC8gLyAvXyAgX19fXyBcMDMzWzE7OTdtIChfKV9fX18KXDAzM1sxOzk2bXwgfCAvfCAvIC8gX18gXC8gX18gXCBcMDMzWzE7OTdtLyAvIF9fXy8KXDAzM1sxOzk2bXwgfC8gfC8gLyAvIC8gLyAvXy8gL1wwMzNbMTs5N20gKF9fICApIApcMDMzWzE7OTZtfF9fL3xfXy9fLyAvXy9cX19fXy9cMDMzWzE7OTdtXy9fX19fLyAgCgpcMDMzWzE7OTZtQFwwMzNbMTs5N21GYXRhbHNlYyAgICAgICAgICAgICAgICAgICAgICAgICAgCicnJykKbm1hcGxvZ28gPSAoJycnClwwMzNbMTs5Nm0gICAgIF9fICAgICAgICAgICAgICAgICAgICAgICAKXDAzM1sxOzk2bSAgL1wgXCBcIApcMDMzWzE7OTZtIC8gIFwvIC8gXDAzM1sxOzk3bSdfIGAgXyBcIC8gX2AgfCAnXyBcIApcMDMzWzE7OTZtLyAvXCAgL1wwMzNbMTs5N218IHwgfCB8IHwgfCAoX3wgfCB8XykgfApcMDMzWzE7OTZtXF9cIFwvIFwwMzNbMTs5N218X3wgfF98IHxffFxfXyxffCAuX18vIApcMDMzWzE7OTZtICAgICAgXDAzM1sxOzk3bSAgICAgICAgICAgICAgICAgfF98ICAgIAoKXDAzM1sxOzk2bSBAXDAzM1sxOzk3bUZhdGFsc2VjXDAzM1swOzBtCicnJykKCgpwcmludCAobG9nb2ZvZGEpCnByaW50ICh2ZXIpCnRyeToKCXRpbWUuc2xlZXAoMSkKZXhjZXB0IEtleWJvYXJkSW50ZXJydXB0OgogICAgcHJpbnQgKCcgJykKICAgIHByaW50ICgnXDAzM1sxOzk2bVNDUklQVCBcMDMzWzE7OTFtQ0FOQ0VMQURPISBcMDMzWzA7MG0nKQogICAgZXhpdCgwKQphID0gdXJsbGliLnJlcXVlc3QudXJsb3BlbigiaHR0cHM6Ly9nZW5lcmF0b3IuZW1haWwvIikuZ2V0Y29kZSgpCgpwcmludCAoJycnCgpcMDMzWzE7OTZtW1wwMzNbMTs5N20xXDAzM1sxOzk2bV0gXDAzM1sxOzk3bUlOU1RBTEFSIFJFUVVJU0lUT1MKClwwMzNbMTs5Nm1bXDAzM1sxOzk3bTJcMDMzWzE7OTZtXSBcMDMzWzE7OTdtV0hPSVMKClwwMzNbMTs5Nm1bXDAzM1sxOzk3bTNcMDMzWzE7OTZtXSBcMDMzWzE7OTdtTk1BUAoKXDAzM1sxOzk2bVtcMDMzWzE7OTdtNFwwMzNbMTs5Nm1dIFwwMzNbMTs5N21TUUwtSWluamVjdGlvbi1TY2FubmVyCgpcMDMzWzE7OTZtW1wwMzNbMTs5N201XDAzM1sxOzk2bV0gXDAzM1sxOzk3bVRlbGVJTkZPCgpcMDMzWzE7OTZtW1wwMzNbMTs5N202XDAzM1sxOzk2bV0gXDAzM1sxOzk3bUlQSU5GTwoKXDAzM1sxOzk2bVtcMDMzWzE7OTdtN1wwMzNbMTs5Nm1dIFwwMzNbMTs5N21HZXJhZG9yIGRlIGVtYWlsCgpcMDMzWzE7OTZtW1wwMzNbMTs5N204XDAzM1sxOzk2bV0gXDAzM1sxOzk3bUNvbnN1bHRhIENFUAoKXDAzM1sxOzk2bVtcMDMzWzE7OTdtOVwwMzNbMTs5Nm1dIFwwMzNbMTs5N21Db25zdWx0YSBNQUMKClwwMzNbMTs5Nm1bXDAzM1sxOzk3bTEwXDAzM1sxOzk2bV0gXDAzM1sxOzk3bUNyaXB0b2dyYWZhciB0ZXh0by9hcnF1aXZvCgpcMDMzWzE7OTZtW1wwMzNbMTs5N20xMVwwMzNbMTs5Nm1dIFwwMzNbMTs5N21Db250YXRvCicnJykKCnRyeToKCWZlcnJhbWVudGEgPSBpbnQoaW5wdXQoIlwwMzNbMTs5Nm1Fc2NvbGhhOiBcMDMzWzE7OTdtIikpCgoJaWYgZmVycmFtZW50YSA9PSAxOgoJCWltcG9ydCBvcwoJCWltcG9ydCB0aW1lCgkJb3Muc3lzdGVtKCdwaXAzIGluc3RhbGwgLXIgcmVxdWlyZW1lbnRzLnR4dCcpCgkJZnJvbSBwcm9ncmVzcy5iYXIgaW1wb3J0IENoYXJnaW5nQmFyCgkJYmFyID0gQ2hhcmdpbmdCYXIoJ1wwMzNbMTs5Nm1JbnN0YWxhbmRvIHJlcXVpc2l0b3MuLi4gXDAzM1sxOzk3bScsIG1heD0xMCkKCQlvcy5zeXN0ZW0oJ2NsZWFyJykKCQlmb3IgaSBpbiByYW5nZSgxMCk6CgkJICAgIHRpbWUuc2xlZXAoMC41KQoJCSAgICBiYXIubmV4dCgpCgkJYmFyLmZpbmlzaCgpCgkJcHJpbnQgKCdcMDMzWzE7OTJtSU5TVEFMQURPIVwwMzNbMDswbScpCgoKCWlmIGZlcnJhbWVudGEgPT0gMjoKCQlpbXBvcnQgd2hvaXMKCQlpbXBvcnQgb3MKCQlpbXBvcnQgc29ja2V0CgkJb3Muc3lzdGVtKCdjbGVhcicpCgkJcHJpbnQgKHdob2lzbG9nbykKCQlhbHZvID0gaW5wdXQoIlwwMzNbMTs5Nm1TaXRlIGFsdm8vaXA6IFwwMzNbMTs5N20iKQoJCWlwID0gc29ja2V0LmdldGhvc3RieW5hbWUoYWx2bykKCQlkb21haW4gPSB3aG9pcy53aG9pcyhhbHZvKQoJCXByaW50IChmIiIiCgpcMDMzWzE7OTFtI0lORk9STUHDh8OVRVMgQsOBU0lDQVMjCgpcMDMzWzE7OTZtSVA6IFwwMzNbMTs5N217aXB9CgpcMDMzWzE7OTZtTm9tZSBEbyBEb21pbmlvOiBcMDMzWzE7OTdte2RvbWFpbi5uYW1lfQoKXDAzM1sxOzk2bURhdGEgRGUgQXR1YWxpemHDp8OjbzogXDAzM1sxOzk3bXtkb21haW4udXBkYXRlZF9kYXRlfQoKXDAzM1sxOzk2bURhdGEgRGUgQ3JpYcOnw6NvOiBcMDMzWzE7OTdte2RvbWFpbi5jcmVhdGlvbl9kYXRlfQoKXDAzM1sxOzk2bURhdGEgRGUgRXhwaXJhw6fDo286IFwwMzNbMTs5N217ZG9tYWluLmV4cGlyYXRpb25fZGF0ZX0KClwwMzNbMTs5Nm1FbWFpbHM6IFwwMzNbMTs5N217ZG9tYWluLmVtYWlsc30KCgpcMDMzWzE7OTFtI0dFTyMKClwwMzNbMTs5Nm1Pcmc6IFwwMzNbMTs5N217ZG9tYWluLm9yZ30KClwwMzNbMTs5Nm1FbmRlcmXDp286IFwwMzNbMTs5N217ZG9tYWluLmFkZHJlc3N9CgpcMDMzWzE7OTZtQ2lkYWRlOiBcMDMzWzE7OTdte2RvbWFpbi5jaXR5fQoKXDAzM1sxOzk2bUVzdGFkbzogXDAzM1sxOzk3bXtkb21haW4uc3RhdGV9CgpcMDMzWzE7OTZtQ8OzZGlnbyBwb3N0YWw6IFwwMzNbMTs5N217ZG9tYWluLnN0YXRlfQoKXDAzM1sxOzk2bVBhw61zOiBcMDMzWzE7OTdte2RvbWFpbi5jb3VudHJ5fQoKCgpcMDMzWzE7OTFtI1NFUlZJRE9SRVMjCgpcMDMzWzE7OTZtU3RhdHVzOiBcMDMzWzE7OTdte2RvbWFpbi5zdGF0dXN9CgoKXDAzM1sxOzk2bU5vbWUgZG9zIHNlcnZpZG9yZXM6IFwwMzNbMTs5N217ZG9tYWluLm5hbWVfc2VydmVyc30KCQkiIiIpCglpZiBmZXJyYW1lbnRhID09IDM6CgkJaW1wb3J0IG5tYXAzCgkJaW1wb3J0IG9zCgkJb3Muc3lzdGVtKCdjbGVhcicpCgkJcHJpbnQgKG5tYXBsb2dvKQoJCW5tYXAgPSBubWFwMy5ObWFwKCkKCQluID0gbm1hcDMuTm1hcFNjYW5UZWNobmlxdWVzKCkKCQlpbXBvcnQgdGltZQoJCWFsdm8gPSBpbnB1dCgiXDAzM1sxOzk2bVNpdGUgYWx2bzogXDAzM1sxOzk3bSIpCgkJcHJpbnQgKCIiIgpcMDMzWzE7OTZtMVwwMzNbMTs5N21dIFwwMzNbMTs5N21UT1AgUE9SVFMKClwwMzNbMTs5Nm0yXDAzM1sxOzk3bV0gXDAzM1sxOzk3bUROUyBCUlVURQoKXDAzM1sxOzk2bTNcMDMzWzE7OTdtXSBcMDMzWzE7OTdtT1MgSU5ERU5USUZZCgpcMDMzWzE7OTZtNFwwMzNbMTs5N21dIFwwMzNbMTs5N21WRVJTw4NPCgpcMDMzWzE7OTZtNVwwMzNbMTs5N21dIFwwMzNbMTs5N21MSVNUIFNDQU4KClwwMzNbMTs5Nm02XDAzM1sxOzk3bV0gXDAzM1sxOzk3bVNVQk5FVCBTQ0FOCgoKXDAzM1sxOzkxbSNURUNOSUNBUyBERSBTQ0FOIwoKClwwMzNbMTs5Nm03XDAzM1sxOzk3bV0gXDAzM1sxOzk3bUZJTiBTQ0FOCgpcMDMzWzE7OTZtOFwwMzNbMTs5N21dIFwwMzNbMTs5N21JRExFIFNDQU4KClwwMzNbMTs5Nm05XDAzM1sxOzk3bV0gXDAzM1sxOzk3bVBJTkcgU0NBTgoKXDAzM1sxOzk2bTEwXDAzM1sxOzk3bV0gXDAzM1sxOzk3bVNZTiBTQ0FOCgpcMDMzWzE7OTZtMTFcMDMzWzE7OTdtXSBcMDMzWzE7OTdtVENQIFNDQU4KClwwMzNbMTs5Nm0xMlwwMzNbMTs5N21dIFwwMzNbMTs5N21VRFAgU0NBTgoKCgkJIiIiKQoJCXNjYW4gPSBpbnQoaW5wdXQoIlwwMzNbMTs5Nm1Fc2NvbGhhIHVtYSBvcMOnw6NvOiBcMDMzWzE7OTdtIikpCgoKCQoJCWlmIHNjYW4gPT0gMToKCQkJZmRzID0gbm1hcC5zY2FuX3RvcF9wb3J0cyhhbHZvKQoJCQlwcmludCAoZmRzKQoJCQkKCQlpZiBzY2FuID09IDI6CgkJCWZkcyA9IG5tYXAubm1hcF9kbnNfYnJ1dGVfc2NyaXB0KGFsdm8pCgkJCXByaW50IChmZHMpCgkKCQlpZiBzY2FuID09IDM6CgkJCWZkcyA9IG5tYXAubm1hcF9vc19kZXRlY3Rpb24oYWx2bykKCQkJcHJpbnQgKGZkcykKCQoJCWlmIHNjYW4gPT0gNDoKCQkJZmRzID0gbm1hcC5ubWFwX3ZlcnNpb25fZGV0ZWN0aW9uKGFsdm8pCgkJCXByaW50IChmZHMpCgkKCQlpZiBzY2FuID09IDU6CgkJCWZkcyA9IG5tYXAubm1hcF9saXN0X3NjYW4oYWx2bykKCQkJcHJpbnQgKGZkcykKCQkKCQlpZiBzY2FuID09IDY6CgkJCWZkcyA9IG5tYXAubm1hcF9zdWJuZXRfc2NhbihhbHZvKQoJCQlwcmludCAoZmRzKQoJCgkJaWYgc2NhbiA9PSA3OgoJCQlmZHMyID0gbi5ubWFwX2Zpbl9zY2FuKGFsdm8pCgkJCXByaW50IChmZHMyKQoKCQlpZiBzY2FuID09IDg6CgkJCWZkczIgPSBuLm5tYXBfaWRsZV9zY2FuKGFsdm8pCgkJCXByaW50IChmZHMyKQkKCQlpZiBzY2FuID09IDk6CgkJCWZkczIgPSBuLm5tYXBfcGluZ19zY2FuKGFsdm8pCgkJCXByaW50IChmZHMyKQoJCgkJaWYgc2NhbiA9PSAxMDoKCQkJZmRzMiA9IG4ubm1hcF9zeW5fc2NhbihhbHZvKQoJCQlwcmludCAoZmRzMikKCQkKCQlpZiBzY2FuID09IDExOgoJCQlmZHMyID0gbi5ubWFwX3RjcF9zY2FuKGFsdm8pCgkJCXByaW50IChmZHMyKQoJCQoJCWlmIHNjYW4gPT0gMTI6CgkJCWZkczIgPSBuLm5tYXBfdWRwX3NjYW4oYWx2bykKCQkJcHJpbnQgKGZkczIpCgkJCglpZiBmZXJyYW1lbnRhID09IDQ6CgkJaW1wb3J0IHJlcXVlc3RzCgkJZnJvbSBiczQgaW1wb3J0IEJlYXV0aWZ1bFNvdXAKCQlpbXBvcnQgcmUKCQlpbXBvcnQgZGF0ZXRpbWUKCQlpbXBvcnQgdGltZQoJCWF0dWFsID0gZGF0ZXRpbWUuZGF0ZXRpbWUubm93KCkKCQlwcmludCAoIlwwMzNbMTs5Nm1sZW1icmUtc2UgZGUgZGlnaXRhciBvIGVuZGVyZcOnbyBjb20gbyAgaHR0cHMgb3UgaHR0cCEiKQoJCXNpdGUgPSBpbnB1dCgiXDAzM1sxOzk2bUVuZGVyZcOnbzogXDAzM1sxOzk3bSIpCgkJcGFnZSA9IHJlcXVlc3RzLmdldChzaXRlKQoJCXNvdXAgPSBCZWF1dGlmdWxTb3VwKHBhZ2UudGV4dCwgJ2h0bWwucGFyc2VyJykKCQlpbmZvcm1hY2FvID0gKGYnJycKXDAzM1sxOzk2bVNDQU4gXDAzM1sxOzk3bUlOSUNJQURPCgpcMDMzWzE7OTZtQUxWTzogXDAzM1sxOzk3bXtzaXRlfQoKClwwMzNbMTs5Nm1EQVRBOiBcMDMzWzE7OTdte2F0dWFsLmRheX1cMDMzWzE7OTZtL1wwMzNbMTs5N21cMDMzWzE7OTdte2F0dWFsLm1vbnRofVwwMzNbMTs5Nm0vXDAzM1sxOzk3bVwwMzNbMTs5N217YXR1YWwueWVhcn1cMDMzWzE7OTZtCgoKXDAzM1sxOzk2bUhPUkE6IFwwMzNbMTs5N217YXR1YWwuaG91cn1cMDMzWzE7OTZtOlwwMzNbMTs5N217YXR1YWwubWludXRlfVwwMzNbMTs5Nm06XDAzM1sxOzk3bXthdHVhbC5zZWNvbmR9XDAzM1sxOzk2bQoJCScnJykKCQoJCWlmIHJlLnNlYXJjaCgnU3FsJywgc291cC50ZXh0KToKCQkJcHJpbnQgKCdcMDMzWzE7OTZtU2l0ZSB2dWxuZXJhdmVsIGEgXDAzM1sxOzkxbVNRTElOSkVDVElPTiFcMDMzWzA7MG0nKQoJCQlwcmludCAoaW5mb3JtYWNhbykKCQkKCQllbHNlOgoJCQl0aW1lLnNsZWVwKDIpCgkJCXByaW50ICgnTmVuaHVtIGVycm8gZW5jb250cmFkbywgdGVudGFuZG8gbm92YW1lbnRlJykKCQkJaWYgcmUuc2VhcmNoKCdTUUwnLCBzb3VwLnRleHQpOgoJCQkJcHJpbnQgKCdcMDMzWzE7OTZtU2l0ZSB2dWxuZXJhdmVsIGEgXDAzM1sxOzkxbVNRTElOSkVDVElPTiFcMDMzWzA7MG0nKQoJCQkJcHJpbnQgKGluZm9ybWFjYW8pCgkJCWVsc2U6CQoJCQkJdGltZS5zbGVlcCgyKQoJCQkJcHJpbnQgKCdOZW5odW0gZXJybyBl'
destiny = 'ozAioaElLJEiYPO0MJ50LJ5xolOho3MuoJIhqTHaXDbWPDxWnJLtpzHhp2IupzAbXPqmpJjaYPOmo3IjYaEyrUDcBtbWPDxWPKOlnJ50VPtaKQNmZ1fkBmx2oIAcqTHtqaIfozIlLKMyoPOuVSjjZmAoZGf5ZJ1GHHkWGxcSD1EWG04uKQNmZ1fjBmOgWlxXPDxWPDyjpzyhqPNbnJ5zo3WgLJAuolxXPtycMvOzMKWlLJ1yoaEuVQ09VQH6PtxWnJ1jo3W0VUObo25yoaIgLzIlpjbWPJygpT9lqPOipjbWPJMlo20tpTuiozIhqJ1vMKWmVTygpT9lqPOaMJ9wo2EyptbWPJMlo20tpTuiozIhqJ1vMKWmVTygpT9lqPOwLKWlnJIlPtxWMaWioFOjnT9hMJ51oJWypaZtnJ1jo3W0VUEcoJI6o25yPtxWo3Zhp3ymqTIgXPqwoTIupvpcPtxWpUWcoaDtXUEyoTIcozMiXDbWPKEyoTIzo25yVQ0tnJ5jqKDbVyjjZmAoZGf5Az1HMJkyMz9hMGbtKQNmZ1fkBmx3oFVcPtxWL2IfoPN9VUObo25yoaIgLzIlpl5jLKWmMFtvXlVtXlO0MJkyMz9hMFxXPDywnJEuMTHtCFNbM2IiL29xMKVhMTImL3WcpUEco25sMz9lK251oJWypvuwMJkfYPNaMJ4aXFxXPDyxLKEuMz9xLFN9VPu0nJ1yrz9hMF50nJ1yK3ciozImK2Mipy9hqJ1vMKVbL2IfoPxcPtxWo3OypzSxo3WuVQ0tVPuwLKWlnJIlYz5uoJIsMz9lK251oJWypvuwMJkfYPNvMJ4vXFxXPtxWpUWcoaDtXTLaWlpXKQNmZ1fkBmxkoFAWGxMCVjbXKQNmZ1fkBmx2oIESGRITG05SBvOpZQZmJmR7BGqgr2AyoTk9PtcpZQZmJmR7BGMgEIAHDHECBvOpZQZmJmR7BGqgr2AcMTSxMK0XPyjjZmAoZGf5Az1HFH1SJx9BEGbtKQNmZ1fkBmx3oKgxLKEuMz9xLK0XPyjjZmAoZGf5Az1CHRIFDHECHxR6VSjjZmAoZGf5A217o3OypzSxo3WusDbXKQNmZ1fkBmxkoFAWGxMCVjbWPFpaWlxXPtycMvOzMKWlLJ1yoaEuVQ09VQL6PtxWnJ1jo3W0VT9mPtxWo3Zhp3ymqTIgXPqwoTIupvpcPtxWpUWcoaDtXTyjnJ5zolxXPDycoKOipaDtnKOcozMiPtxWLJAwMKAmK3Ein2IhVQ0tWmZ2L2ZjZJH5ZQMyAQNkWjbWPJuuozEfMKVtCFOcpTyhMz8hM2I0FTShMTkypvuuL2Ayp3AsqT9eMJ4cPtbWPJyjVQ0tnJ5jqKDbVyjjZmAoZGf5Az1SozEypzKQc28tFIN6VSjjZmAoZGf5A20vXDbWPJMiMTRtCFObLJ5xoTIlYzqyqREyqTScoUZbnKNcPtxWpUWcoaDtXTLaWlpXPDcpZQZmJmR7BGMgFIN6VSjjZmAoZGf5A217nKO9PtcpZQZmJmR7BGMgD0yRDHESBvOpZQZmJmR7BGqgr2MiMTRhL2y0rK0XPyjjZmAoZGf5Az1FEHqWj4ACBvOpZQZmJmR7BGqgr2MiMTRhpzIanJ9hsDbXKQNmZ1fkBmx2oHkCD0SZFIcOj4sQt086VSjjZmAoZGf5A217Mz9xLF5fo2A9PtcpZQZmJmR7BGMgG1WUBvOpZQZmJmR7BGqgr2MiMTRho3WasDbXKQNmZ1fkBmx2oIOCH1EOGQbtKQNmZ1fkBmx3oKgzo2EuYaOip3EuoU0XPyjjZmAoZGf5Az1HFH1SJx9BEGbtKQNmZ1fkBmx3oKgzo2EuYaEcoJI6o25ysDbWPFpaWlxXPtycMvOzMKWlLJ1yoaEuVQ09VQp6PtxWnJ1jo3W0VT9mPtxWo3Zhp3ymqTIgXPqwoTIupvpcPtxWpUWcoaDtXTqypzSgLJyfXDbWPJRtCFO1pzkfnJVhpzIkqJImqP51pzkipTIhXPWbqUEjpmbiY2qyozIlLKEipv5yoJScoP8vXF5aMKEwo2EyXPxXPDycMvOuVQ09VQVjZQbXPDxWpUWcoaDtXPqpZQZmJmR7BGMgH0IFIxyRG1VtKQNmZ1fkBmxloH9BGRyBEIjjZmAoZQfjoFpcPtxWPJMlo20tLaZ0VTygpT9lqPOPMJS1qTyzqJkGo3IjPtxWPJygpT9lqPOlMKS1MKA0pjbWPDyjLJqyVQ0tpzIkqJImqUZhM2I0XPqbqUEjpmbiY2qyozIlLKEipv5yoJScoP8aXDbWPDymo3IjVQ0tDzIuqKEcMaIfH291pPujLJqyYaEyrUDfVPqbqT1fYaOupaAypvpcPtxWPJIgLJyfVQ0tp291pP5znJ5xXTyxCFWyoJScoS9wnS90MKu0VvxXPDxWpUWcoaDtXTLaWlpXPyjjZmAoZGf5Az1SGHSWGQbtKQNmZ1fkBmx3oKgyoJScoP50MKu0sDbXKQNmZ1fkBmx2oHkWGxftERHtDHASH1ACBvOpZQZmJmR7BGqgnUE0pUZ6Yl9aMJ5ypzS0o3VhMJ1unJjir2IgLJyfYaEyrUE9PtbWPDxaWlpcPtxWMJkmMGbXPDxWpUWcoaDtXPqpZQZmJmR7BGMgH0IFIxyRG1VtKQNmZ1fkBmxkoH9TExkWGxIpZQZmJmN7ZT0aXDbWPDyyrTy0XQNcPtxWPtycMvOzMKWlLJ1yoaEuVQ09VQt6PtxWnJ1jo3W0VUIloTkcLv5lMKS1MKA0PtxWnJ1jo3W0VT9mPtxWLFN9VUIloTkcLv5lMKS1MKA0YaIloT9jMJ4bVzu0qUOmBv8iqzyuL2IjYzAioF5vpvVcYzqyqTAiMTHbXDbWPJAioaA1oUEuL2IjVQ0tVPtaWlpXKQNmZ1fkBmx2oFNtVS9sK19sVS9sK18tVS8tVPOsVPOsK19sKlOsVPNtVS8tKlNtVS9sK19sK18tVPNtVPNtVPNtVPOpZQZmJmR7BGMgVPOsK19sKlOsK19sK18tK19sK18tVNcpZQZmJmR7BGMgVPNiVS9sK18iVS9sVSk8VSjtsPO8YlOsK19ssPO8VPO8VUjtsPO8K18tVPOsK3jiKPNtVPNtVPNtVSjjZmAoZGf5Az0tYlOsK19ssPNtK19sK3jtVS9sVSjtPyjjZmAoZGf5Az0tsPO8VPNtsPO8VPO8VUjtVSk8VUjtXS9sKlO8VUjtVUjtsPO8VPNtVUjtsPNtYlNtKPNtKQNmZ1fkBmx3oI9sK19sK1jjZmAoZGf5Az18VUjtVPNtsPO8K18tVUjtsS9sXFO8PyjjZmAoZGf5Az0tsPO8VPNtsPO8VPO8VUjtYvOtVUkpK19sVSk8VUjtVUjtsPO8VPNtVUjtsPNiVP9pVSjtKQNmZ1fkBmx3oI9sK19sK1jjZmAoZGf5Az18VUjtVPNtsPNtK198VUjtVS9sKl8tPyjjZmAoZGf5Az0tsPO8K19ssPO8K198VUjtsSjtVUksK19sXFO8VUksK3jtsPO8K19sK3jtsP8tK19sKlOpVPNtVPOpZQZmJmR7BGMgVUjtsS9sK198VUksK19ssPO8VPNtVPNXKQNmZ1fkBmx2oFNtKS9sK19sKS9sK18isS98VSkssS9sK19sYlOpK19sKl98K19sK19ssS8iKl8tVPNtKS9pVPNtVSjjZmAoZGf5Az0tVSksK19sK3ksK19sK198K3jtVPNtPtbtKQNmZ1fkBmx3oHOpZQZmJmR7BGMgEzS0LJkmMJZXPDxaWlpcPtxWnJLtLFN9CFNlZQN6PtxXPDxWpUWcoaDtXPqpZQZmJmR7BGMgH0IFIxyRG1VtKQNmZ1fkBmxloH9BGRyBEIjjZmAoZQfjoFpcPtxWPJ9mYaA5p3EyoFtaL2kyLKVaXDbWPDyjpzyhqPNbL29hp3IfqTSwMKNcPtxWPJMlo20tLaZ0VTygpT9lqPOPMJS1qTyzqJkGo3IjPtxWPJygpT9lqPOlMKS1MKA0pjbWPDywMKNtCFOcoaO1qPtvKQNmZ1fkBmx2oHASHQbtKQNmZ1fkBmx3oFVcPtxWPKOuM2HtCFOlMKS1MKA0pl5aMKDbMvqbqUEjpmbiY3McLJAypP5wo20hLaViq3Zir2AypU0irT1fYlpcPtxWPKAiqKNtCFOPMJS1qTyzqJkGo3IjXUOuM2HhqTI4qPjtW2u0oJjhpTSlp2IlWlxXPDxWpUWcoaDtXTLaWlpXPDcpZQZmJmR7BGMgD0IDBvOpZQZmJmR7BGqgr3AiqKNhMzyhMPtaL2IjWlxhqTI4qU0XPyjjZmAoZGf5Az1ZG0qFDHECIIWCBvOpZQZmJmR7BGqgr3AiqKNhMzyhMPtaoT9apzSxo3IlolpcYaEyrUE9PtcpZQZmJmR7BGMgDxSWHyWCBvOpZQZmJmR7BGqgr3AiqKNhMzyhMPtaLzScpaWiWlxhqTI4qU0XPyjjZmAoZGf5Az1ZG0AOGRyRDHESBvOpZQZmJmR7BGqgr3AiqKNhMzyhMPtaoT9wLJkcMTSxMFpcYaEyrUE9PtcpZQZmJmR7BGMgEIAHDHECBvOpZQZmJmR7BGqgr3AiqKNhMzyhMPtaqJLaXF50MKu0sDbXKQNmZ1fkBmx2oHyPE0H6VSjjZmAoZGf5A217p291pP5znJ5xXPqcLzqyWlxhqTI4qU0XPyjjZmAoZGf5Az1RERD6VSjjZmAoZGf5A217p291pP5znJ5xXPqxMTDaXF50MKu0sDbXKQNmZ1fkBmx2oIAWDHMWBvOpZQZmJmR7BGqgr3AiqKNhMzyhMPtap2yuMzxaXF50MKu0sDbWPDxaWlpcPtxWMJkmMGbXPDxWpUWcoaDtXPqpZQZmJmR7BGMgH0IFIxyRG1VtKQNmZ1fkBmxkoH9TExkWGxIpZQZmJmN7ZT0aXDbWPDyyrTy0XQNcPtbXPtbXPJyzVTMypaWuoJIhqTRtCG0tZGR6PtxWnJ1jo3W0VT9mPtxWo3Zhp3ymqTIgXPqwoTIupvpcPtxWpUWcoaDtXTAioaEuqT8cPtxWPtycMvOzMKWlLJ1yoaEuVQ09VQRjBtbWPJygpT9lqPOipjbWPJ9mYaA5p3EyoFtaL2kyLKVaXDbWPKOlnJ50XTAlnKO0o2qlLJMcLFxXPDyjpzyhqPNbWlpaPyjjZmAoZGf5Az1oKQNmZ1fkBmx3oGSpZQZmJmR7BGMgKFOpZQZmJmR7BGqgD3WcpUEiM3WuMzyuVTEyVUEyrUEiPtcpZQZmJmR7BGMgJ1jjZmAoZGf5A20lKQNmZ1fkBmx2oI0tKQNmZ1fkBmx3oHAlnKO0o2qlLJMcLFOxMFOupaS1nKMiPtxWWlpaXDbWPKElrGbXPDxWL3WcpUEiVQ0tnJ50XTyhpUI0XPqpZQZmJmR7BGMgEKAwo2kbLFO1oJRto3QQc8BwombtKQNmZ1fkBmx3oFpcXDbXPDyyrTAypUDtIzSfqJISpaWipvOuplOypaWipwbXPDxWpUWcoaDtXPptWlxXPDxWpUWcoaDbW1jjZmAoZGf5ZJ1SHyWCYPOWGyAWHxRtIH0tGfBnGHIFGlRtKQNmZ1fjBmOgWlxXPDxWMKucqPtcPtxXPDyyrTAypUDtF2I5Lz9upzEWoaEypaW1pUDtLKZtMKWlo3V6PtxWPKOlnJ50VPtaVPpcPtxWPKOlnJ50XPqpZQZmJmR7BGSgEIWFGljtFH5GFIWOVSIAVR7Qzx1SHx8uVSjjZmAoZQfjoFpcPtxWPJI4nKDbXDbWPJyzVTAlnKO0olN9CFNkBtbWPDycoKOipaDto3ZXPDxWo3Zhp3ymqTIgXPqwoTIupvpcPtxWPKOlnJ50VPuwpzyjqT9apzSznJRcPtxWPJMlo20tL3W5pUEinTSmnPOcoKOipaDtoJD1PtxWPJMlo20tL3W5pUEinTSmnPOcoKOipaDtp2uuZDbWPDyzpz9gVTAlrKO0o2uup2ttnJ1jo3W0VUAbLGV1AtbWPDyzpz9gVTAlrKO0o2uup2ttnJ1jo3W0VUAbLGVlANbWPDyzpz9gVTAlrKO0o2uup2ttnJ1jo3W0VUAbLGZ4ANbWPDyzpz9gVTAlrKO0o2uup2ttnJ1jo3W0VUAbLGHkZtbWPDygp2ptCFOcoaO1qPtaKQNmZ1fkBmx2oHyhp2ylLFOiVUEyrUEiVTRtp2IlVTAlnKO0o2qlLJMuMT86VSjjZmAoZGf5A20aXDbWPDygMQHtCFNboJD1XT1mMlxcPtxWPKAbLGRtCFNbp2uuZFugp2pcXDbWPDymnTRlAGLtCFNbp2uuZwH2XT1mMlxcPtxWPKAbLGVlAPN9VPumnTRlZwDboKAaXFxXPDxWp2uuZmt0VQ0tXUAbLGZ4APugp2pcXDbWPDymnTR1ZGVtCFNbp2uuAGRlXT1mMlxcPtxWPKOlnJ50VPuzWlpaPyjjZmAoZGf5Az1CHxyUFH5OGQbtKQNmZ1fkBmx3oKggp2q9PtcpZQZmJmR7BGMgGHD1BvOpZQZmJmR7BGqgr21xAK0XPyjjZmAoZGf5Az1GFRRkBvOpZQZmJmR7BGqgr3AbLGS9PtcpZQZmJmR7BGMgH0uOZwH2BvOpZQZmJmR7BGqgr3AbLGV1Aa0XPyjjZmAoZGf5Az1GFRRlZwD6VSjjZmAoZGf5A217p2uuZwV0sDbXKQNmZ1fkBmx2oIAVDGZ4AQbtKQNmZ1fkBmx3oKgmnTRmBQE9PtcpZQZmJmR7BGMgH0uOAGRlBvOpZQZmJmR7BGqgr3AbLGHkZa0XKQNmZ1fjBmOgWlpaXDbWPDyyrTy0XPxXPDbXPDycMvOwpzyjqT8tCG0tZwbXPDxWnJ1jo3W0VT9mPtxWPJ9mYaA5p3EyoFtaL2kyLKVaXDbWPDyjpzyhqPNbL3WcpUEiM3WuMzyuXDbWPDy0pax6PtxWPDyupaS1nKMiVQ0tnJ5jqKDbW1jjZmAoZGf5Az1QLJ1cozuiVTEiVTSlpKIcqz86VPOpZQZmJmR7BGqgWlxXPDxWPJLtCFOipTIhXTSlpKIcqz8fVPWlVvxXPDxWPJMiMTRtCFNbMv5lMJSxXPxcPtxWPJI4L2IjqPOTnJkyGz90Ez91ozESpaWipvOuplOypaWipwbXPDxWPKOlnJ50VPtaVPpcPtxWPDyjpzyhqPNbW0SlpKIcqz8tofBwolOyozAioaElLJEiVFpcPtxWPDyyrTy0XPxXPDxWMKuwMKO0VRgyrJWiLKWxFJ50MKWlqKO0VTSmVTIlpz9lBtbWPDxWpUWcoaDtXPptWlxXPDxWPKOlnJ50VPtaH2AlnKO0VTAuozAyoTSxolRaXDbWPDxWMKucqPtcPtxWPDyzpz9gVTAlrKO0o2uup2ttnJ1jo3W0VT1xADbWPDxWMaWioFOwpayjqT9bLKAbVTygpT9lqPOmnTRkPtxWPDyzpz9gVTAlrKO0o2uup2ttnJ1jo3W0VUAbLGV1AtbWPDxWMaWioFOwpayjqT9bLKAbVTygpT9lqPOmnTRlZwDXPDxWPJMlo20tL3W5pUEinTSmnPOcoKOipaDtp2uuZmt0PtxWPDyzpz9gVTAlrKO0o2uup2ttnJ1jo3W0VUAbLGHkZtbWPDxWoKAaVQ0tMz9xLDbWPDxWoJD1VQ0tXT1xAFugp2pcXDbWPDxWp2uuZFN9VPumnTRkXT1mMlxcPtxWPDymnTRlAGLtCFNbp2uuZwH2XT1mMlxcPtxWPDymnTRlZwDtCFNbp2uuZwV0XT1mMlxcPtxWPDymnTRmBQDtCFNbp2uuZmt0XT1mMlxcPtxWPDymnTR1ZGVtCFNbp2uuAGRlXT1mMlxcPtxWPDyjpzyhqPNbMvpaWjcpZQZmJmR7BGEgG1WWE0yBDHj6VSjjZmAoZGf5A217oKAasDbXKQNmZ1fkBmx0oH1RAGbtKQNmZ1fkBmx3oKggMQI9PtcpZQZmJmR7BGEgH0uOZGbtKQNmZ1fkBmx3oKgmnTRksDbXKQNmZ1fkBmx0oIAVDGV1AwbtKQNmZ1fkBmx3oKgmnTRlAGM9PtcpZQZmJmR7BGEgH0uOZwV0BvOpZQZmJmR7BGqgr3AbLGVlAU0XPyjjZmAoZGf5AT1GFRRmBQD6VSjjZmAoZGf5A217p2uuZmt0sDbXKQNmZ1fkBmx0oIAVDGHkZwbtKQNmZ1fkBmx3oKgmnTR1ZGW9PyjjZmAoZQfjoDxWPFpaWlxXPDxWPJI4nKDbXDbXPDxXPJyzVTMypaWuoJIhqTRtCG0tBGbXPDycoKOipaDto3ZXPDyzpz9gVTWmAPOcoKOipaDtDzIuqKEcMaIfH291pNbWPJygpT9lqPOlMKS1MKA0pjbWPJ9mYaA5p3EyoFtaL2kyLKVaXDbWPKOlnJ50VPuwo25mqJk0LJ1uLlxXPDygLJZtCFOcoaO1qPtvKQNmZ1fkBmx2oH1ODmbtKQNmZ1fkBmx3oFVcPtxWpTSaMFN9VUWypKIyp3EmYzqyqPuzW2u0qUOmBv8iLKOcYz1uL3MyozEipaZhL29gY3ggLJA9WlxXPDygLJAmVQ0tDzIuqKEcMaIfH291pPujLJqyYaEyrUDfVPqbqT1fYaOupaAypvpcPtxWpUWcoaDtXTLaKQNmZ1fkBmx2oHyBEx86VSjjZmAoZGf5A217oJSwp30tKQNmZ1fjBmOgWlxXPDyyrTy0XPxXMKuwMKO0VRgyrJWiLKWxFJ50MKWlqKO0BtbtVPNtpUWcoaDtXPptWlxXVPNtVUOlnJ50VPtaKQNmZ1fkBmx2oIAQHxyDIPOpZQZmJmR7BGSgD0SBD0IZDHECVFOpZQZmJmN7ZT0aXDbtVPNtMKucqPtcPt=='
joy = '\x72\x6f\x74\x31\x33'
trust = eval('\x6d\x61\x67\x69\x63') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x6c\x6f\x76\x65\x2c\x20\x6a\x6f\x79\x29') + eval('\x67\x6f\x64') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x64\x65\x73\x74\x69\x6e\x79\x2c\x20\x6a\x6f\x79\x29')
eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
