#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
#Criptografado por @fatalsec, apenas por segurança mesmo.
#entre em contato >>  https://malito:rootfatalsec@protonmail.ch
import base64, codecs
magic = 'aW1wb3J0IHRpbWUKaW1wb3J0IHVybGxpYi5yZXF1ZXN0CmltcG9ydCByYW5kb20KdmVyID0gKCdcMDMzWzE7OTZtVmVyc8OjbyBcMDMzWzE7OTdtWyBcMDMzWzE7OTZtMS4wLjEgXDAzM1sxOzk3bV0gXDAzM1swOzBtJykKY29uc3VsdGFtYWMgPSAoJycnClwwMzNbMTs5Nm0gX18gICBfXyAgICAgICAgX18gICAgICAgICAgICBfX18gICAgICAgICAgXDAzM1sxOzk2bSAgICAgICAgICAgIF9fICAKXDAzM1sxOzk2bS8gIGAgLyAgXCB8XCB8IC9fX2AgfCAgfCB8ICAgICB8ICAgL1wgIFwwMzNbMTs5N21fXyAgXDAzM1sxOzk2bSB8XC98ICAvXCAgLyAgYCAKXDAzM1sxOzk2bVxfXywgXF9fLyB8IFx8IC5fXy8gXF9fLyB8X19fICB8ICAvfn5cICAgICBcMDMzWzE7OTZtIHwgIHwgL35+XCBcX18sIAoKIFwwMzNbMTs5N21AXDAzM1sxOzk2bUZhdGFsc2VjICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAonJycpCgppbmVlMSA9ICAoJycnCgpcMDMzWzE7OTZt4paI4paI4oCB4paI4paI4paI4oCBICAg4paI4paI4oCB4paI4paI4paI4paI4paI4paI4paI4oCBIOKWiOKWiOKWiOKWiOKWiOKWiOKAgSBcMDMzWzE7OTdt4paI4paI4paI4paI4paI4paI4paI4oCB4paI4paI4paI4paI4paI4paI4paI4oCBIOKWiOKWiOKWiOKWiOKWiOKWiOKAgQpcMDMzWzE7OTZt4paI4paI4oCB4paI4paI4paI4paI4oCBICDilojilojigIHilojilojigIHigIHigIHigIHigIHigIHilojilojigIHigIHigIHigIHilojilojigIFcMDMzWzE7OTdt4paI4paI4oCB4oCB4oCB4oCB4oCB4oCB4paI4paI4oCB4oCB4oCB4oCB4oCB4oCB4paI4paI4oCB4oCB4oCB4oCB4oCB4oCBClwwMzNbMTs5Nm3ilojilojigIHilojilojigIHilojilojigIEg4paI4paI4oCB4paI4paI4paI4paI4paI4oCBICDilojilojigIEgICDilojilojigIFcMDMzWzE7OTdt4paI4paI4paI4paI4paI4paI4paI4oCB4paI4paI4paI4paI4paI4oCBICDilojilojigIEgICAgIApcMDMzWzE7OTZt4paI4paI4oCB4paI4paI4oCB4oCB4paI4paI4oCB4paI4paI4oCB4paI4paI4oCB4oCB4oCB4oCBICDilojilojigIEgICDilojilojigIHigIFcMDMzWzE7OTdt4oCB4oCB4oCB4oCB4paI4paI4oCB4paI4paI4oCB4oCB4oCB4oCBICDilojilojigIEgICAgIApcMDMzWzE7OTZt4paI4paI4oCB4paI4paI4oCBIOKAgeKWiOKWiOKWiOKWiOKAgeKWiOKWiOKAgSAgICAg4oCB4paI4paI4paI4paI4paI4paI4oCBXDAzM1sxOzk3beKAgeKWiOKWiOKWiOKWiOKWiOKWiOKWiOKAgeKWiOKWiOKWiOKWiOKWiOKWiOKWiOKAgeKAgeKWiOKWiOKWiOKWiOKWiOKWiOKAgQoKXDAzM1sxOzk2bUBcMDMzWzE7OTdtRkFUQUxTRUNcMDMzWzA7MG3igIHigIHigIHigIHigIEgIOKAgeKAgeKAgeKAgeKAgeKAgeKAgeKAgSAgICAgIOKAgeKAgeKAgeKAgeKAgeKAgeKAgSDigIHigIHigIHigIHigIHigIHigIHigIHigIHigIHigIHigIHigIHigIHigIHigIEg4oCB4oCB4oCB4oCB4oCB4oCB4oCBCicnJykKCmluZWUyID0gKCcnJwoKXDAzM1sxOzk2beKWiOKWiOKVl+KWiOKWiOKWiOKVlyAgIOKWiOKWiOKVl+KWiOKWiOKWiOKWiOKWiOKWiOKWiOKVlyDilojilojilojilojilojilojilZcgXDAzM1sxOzk3beKWiOKWiOKWiOKWiOKWiOKWiOKWiOKVl+KWiOKWiOKWiOKWiOKWiOKWiOKWiOKVlyDilojilojilojilojilojilojilZcKXDAzM1sxOzk2beKWiOKWiOKVkeKWiOKWiOKWiOKWiOKVlyAg4paI4paI4pWR4paI4paI4pWU4pWQ4pWQ4pWQ4pWQ4pWd4paI4paI4pWU4pWQ4pWQ4pWQ4paI4paI4pWXXDAzM1sxOzk3beKWiOKWiOKVlOKVkOKVkOKVkOKVkOKVneKWiOKWiOKVlOKVkOKVkOKVkOKVkOKVneKWiOKWiOKVlOKVkOKVkOKVkOKVkOKVnQpcMDMzWzE7OTZt4paI4paI4pWR4paI4paI4pWU4paI4paI4pWXIOKWiOKWiOKVkeKWiOKWiOKWiOKWiOKWiOKVlyAg4paI4paI4pWRICAg4paI4paI4pWRXDAzM1sxOzk3beKWiOKWiOKWiOKWiOKWiOKWiOKWiOKVl+KWiOKWiOKWiOKWiOKWiOKVlyAg4paI4paI4pWRICAgICAKXDAzM1sxOzk2beKWiOKWiOKVkeKWiOKWiOKVkeKVmuKWiOKWiOKVl+KWiOKWiOKVkeKWiOKWiOKVlOKVkOKVkOKVnSAg4paI4paI4pWRICAg4paI4paI4pWRXDAzM1sxOzk3beKVmuKVkOKVkOKVkOKVkOKWiOKWiOKVkeKWiOKWiOKVlOKVkOKVkOKVnSAg4paI4paI4pWRICAgICAKXDAzM1sxOzk2beKWiOKWiOKVkeKWiOKWiOKVkSDilZrilojilojilojilojilZHilojilojilZEgICAgIOKVmuKWiOKWiOKWiOKWiOKWiOKWiOKVlOKVnVwwMzNbMTs5N23ilojilojilojilojilojilojilojilZHilojilojilojilojilojilojilojilZfilZrilojilojilojilojilojilojilZcKXDAzM1sxOzk2beKVmuKVkOKVneKVmuKVkOKVnSAg4pWa4pWQ4pWQ4pWQ4pWd4pWa4pWQ4pWdICAgICAg4pWa4pWQ4pWQ4pWQ4pWQ4pWQ4pWdIFwwMzNbMTs5N23ilZrilZDilZDilZDilZDilZDilZDilZ3ilZrilZDilZDilZDilZDilZDilZDilZ0g4pWa4pWQ4pWQ4pWQ4pWQ4pWQ4pWdCgpcMDMzWzE7OTZtQFwwMzNbMTs5N21GQVRBTFNFQ1wwMzNbMDswbeKAgSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAonJycpCgoKaW5lZTMgPSAoJycnClwwMzNbMTs5Nm0jIyMjICMjICAgICMjICMjIyMjIyMjICAjIyMjIyMjICAgXDAzM1sxOzk3bSMjIyMjIyAgIyMjIyMjIyMgICMjIyMjIyAgClwwMzNbMTs5Nm0gIyMgICMjIyAgICMjICMjICAgICAgICMjICAgICAjIyBcMDMzWzE7OTdtIyMgICAgIyMgIyMgICAgICAgIyMgICAgIyMgClwwMzNbMTs5Nm0gIyMgICMjIyMgICMjICMjICAgICAgICMjICAgICAjIyBcMDMzWzE7OTdtIyMgICAgICAgIyMgICAgICAgIyMgICAgICAgClwwMzNbMTs5Nm0gIyMgICMjICMjICMjICMjIyMjIyAgICMjICAgICAjIyBcMDMzWzE7OTdtICMjIyMjIyAgIyMjIyMjICAgIyMgICAgICAgClwwMzNbMTs5Nm0gIyMgICMjICAjIyMjICMjICAgICAgICMjICAgICAjIyAgXDAzM1sxOzk3bSAgICAgIyMgIyMgICAgICAgIyMgICAgICAgClwwMzNbMTs5Nm0gIyMgICMjICAgIyMjICMjICAgICAgICMjICAgICAjIyBcMDMzWzE7OTdtIyMgICAgIyMgIyMgICAgICAgIyMgICAgIyMgClwwMzNbMTs5Nm0jIyMjICMjICAgICMjICMjICAgICAgICAjIyMjIyMjICAgXDAzM1sxOzk3bSMjIyMjIyAgIyMjIyMjIyMgICMjIyMjIyAgCgpcMDMzWzE7OTZtQFwwMzNbMTs5N21GQVRBTFNFQ1wwMzNbMDswbeKAgSAKCicnJykKCmluZWU0ID0gKCcnJwoKXDAzM1sxOzk2bWQ4ODg4ODhiIGQ4YiAgIGRiIGQ4ODg4OGIgIC5kODhiLiAgIFwwMzNbMTs5N20uZDg4ODguIGQ4ODg4OGIgIC5vODhiLiAKXDAzM1sxOzk2bSAgYDg4JyAgIDg4OG8gIDg4IDg4JyAgICAgLjhQICBZOC4gIFwwMzNbMTs5N204OCcgIFlQIDg4JyAgICAgZDhQICBZOCAKXDAzM1sxOzk2bSAgIDg4ICAgIDg4VjhvIDg4IDg4b29vICAgODggICAgODggIFwwMzNbMTs5N21gOGJvLiAgIDg4b29vb28gOFAgICAgICAKXDAzM1sxOzk2bSAgIDg4ICAgIDg4IFY4bzg4IDg4fn5+ICAgODggICAgODggICBcMDMzWzE7OTdtIGBZOGIuIDg4fn5+fn4gOGIgICAgICAKXDAzM1sxOzk2bSAgLjg4LiAgIDg4ICBWODg4IDg4ICAgICAgYDhiICBkOCcgIFwwMzNbMTs5N21kYiAgIDhEIDg4LiAgICAgWThiICBkOCAKXDAzM1sxOzk2bVk4ODg4ODhQIFZQICAgVjhQIFlQICAgICAgIGBZODhQJyAgXDAzM1sxOzk3bSBgODg4OFknIFk4ODg4OFAgIGBZODhQJyAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKXDAzM1sxOzk2bUBcMDMzWzE7OTdtRkFUQUxTRUNcMDMzWzA7MG3igIEgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAonJycpCgoKaW5lZTUgPSAoJycnClwwMzNbMTs5Nm0gX19fX18gX18gICBfIF9fX19fX18gIF9fX19fICAgXDAzM1sxOzk3bV9fX19fX18gX19fX19fXyBfX19fX19fClwwMzNbMTs5Nm0gICB8ICAgfCBcICB8IHxfX19fX18gfCAgICAgfCAgXDAzM1sxOzk3bXxfX19fX18gfF9fX19fXyB8ICAgICAgClwwMzNbMTs5Nm0gX198X18gfCAgXF98IHwgICAgICAgfF9fX19ffCAgXDAzM1sxOzk3bV9fX19fX3wgfF9fX19fXyB8X19fX18gCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgClwwMzNbMTs5Nm1AXDAzM1sxOzk3bUZBVEFMU0VDXDAzM1swOzBt4oCBCicnJykKCgppbmVlNiA9ICgnJycKXDAzM1sxOzk2bSAgICAgICAgICAgICAgICAgICAgICAgICwgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApcMDMzWzE7OTZtICAgICAgICAgICAgICAgICAgICAgICAgIEV0ICAgICAgICAgICA6ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApcMDMzWzE7OTZtICAgICAgIEwuICAgICAgICAgICAgICAgIEUjdCAgICAgICAgIHQjLCAgICAgXDAzM1sxOzk3bSAgICAgIC4gICAgICAgICw7ICAgICAgLiwKXDAzM1sxOzk2bSAgIHQgICBFVzogICAgICAgICxmdCAgICBFIyN0ICAgICAgIDsjI1cuICAgIFwwMzNbMTs5N20gICAgIDtXICAgICAgZiNpICAgICAgLFd0ClwwMzNbMTs5Nm0gICBFaiAgRSMjOyAgICAgICB0I0UgICAgRSNXI3QgICAgIDojTDpXRSAgIFwwMzNbMTs5N20gICAgIGYjRSAgICAuRSN0ICAgICAgaSNELgpcMDMzWzE7OTZtICAgRSMsIEUjIyN0ICAgICAgdCNFICAgIEUjdGZMLiAgIC5LRyAgLCNEIFwwMzNbMTs5N20gICAgLkUjZiAgICBpI1csICAgICAgZiNmICAKXDAzM1sxOzk2bSAgIEUjdCBFI2ZFI2YgICAgIHQjRSAgICBFI3QgICAgICBFRSAgICA7I2YgXDAzM1sxOzk3bSAgaVdXOyAgICBMI0QuICAgICAuRCNpICAgClwwMzNbMTs5Nm0gICBFI3QgRSN0IEQjRyAgICB0I0UgLGZmVyNEZmZqLiBmIy4gICAgIHQjaVwwMzNbMTs5N20gTCMjTGZmaTpLI1dmZmY7ICA6S1csICAgIApcMDMzWzE7OTZtICAgRSN0IEUjdCAgZiNFLiAgdCNFICA7TFcjRUxMTGYuOiNHICAgICBHSyBcMDMzWzE7OTdtdExMRyMjTCBpIyNXTExMTHQgdCNmICAgICAKXDAzM1sxOzk2bSAgIEUjdCBFI3QgICB0I0s6IHQjRSAgICBFI3QgICAgICA7I0wgICBMVy4gXDAzM1sxOzk3bSAgLFcjaSAgIC5FI0wgICAgICA7I0cgICAgClwwMzNbMTs5Nm0gICBFI3QgRSN0ICAgIDsjVyx0I0UgICAgRSN0ICAgICAgIHQjZiBmIzogXDAzM1sxOzk3bSAgaiNFLiAgICAgIGYjRTogICAgIDpLRS4gIApcMDMzWzE7OTZtICAgRSN0IEUjdCAgICAgOksjRCNFICAgIEUjdCAgICAgICAgZiNEIzsgIFwwMzNbMTs5N20uRCNqICAgICAgICAgLFdXOyAgICAgLkRXOiAKXDAzM1sxOzk2bSAgIEUjdCBFI3QgICAgICAuRSMjRSAgICBFI3QgICAgICAgICBHI3QgIFwwMzNbMTs5N20sV0ssICAgICAgICAgICAuRCM7ICAgICAgTCMsClwwMzNbMTs5Nm0gICBFI3QgLi4gICAgICAgICBHI0UgICAgRSN0ICAgICAgICAgIHQgICBcMDMzWzE7OTdtRUcuICAgICAgICAgICAgICB0dCAgICAgICBqdApcMDMzWzE7OTZtICAgLDsuICAgICAgICAgICAgIGZFICAgIDsjdCAgICAgICAgICAgICBcMDMzWzE7OTdtICwgICAgICAgICAgICAgICAgICAgICAgICAgICAKXDAzM1sxOzk2bSAgICAgICAgICAgICAgICAgICAgLCAgICAgOjsgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKClwwMzNbMTs5Nm1AXDAzM1sxOzk3bUZBVEFMU0VDXDAzM1swOzBt4oCBCicnJykKCmluZWU3ID0gKCcnJyAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApcMDMzWzE7OTZtIGA3TU1GJ2A3TU4uICAgYDdNRidgN01NIiIiWU1NICAgLmc4IiI4cS4gICAgXDAzM1sxOzk3bS5'
love = 'AVvVvLzqxVTN3GH0vVvWMGH0tVPNtYzp4VvVvLzqxVNcpZQZmJmR7BGMgVPNtGH0tVPNtGH1BYvNtVPOAVPNtVR1AVPNtVTN3VP5xHPptVPNtLSyAYvOpZQZmJmR7BGqgYR1WVPNtVPWMVPNtGH0tVPNtLQptVP5xHPptVPNtVTOAVNcpZQZmJmR7BGMgVPNtGH0tVPNtGFOMGJVtVPOAVPNtVR1AVPNtMPNtVTEAWlNtVPNtVTOAGFOpZQZmJmR7BGqgLR1ALv4tVPNtVPNtGH0tVPOxVPNtVTEAWlNtVPNtVPOtVNcpZQZmJmR7BGMgVPNtGH0tVPNtGFNtLR1BYvOAVPNtVR1AVvWAGFNtVR1AVPNtVPNtVPOAGFOpZQZmJmR7BGqgVPOtJH1AGaRhVPNtGH1goH1AVPNtVR1AVPNtVPNtVPNtVNcpZQZmJmR7BGMgVPNtGH0tVPNtGFNtVTOAGF5AVPNtVR1AVPNtJFNtVR1AYvNtVPNtVPkAHPOpZQZmJmR7BGqgYvNtVPNtLR1AVPNtGH0tVPOMVPNfVR1AYvNtVPNtVPNtVNcpZQZmJmR7BGMgVPNtGH0tVPNtGFNtVPNtJH1AVPNtVR1AVPNtVPNtVTOALv4tVPNtYTEDW1jjZmAoZGf5A20tGJVtVPNtVTEAVPNtGH0tVPNtVPkAVTOALv4tVPNtVPjaVNcpZQZmJmR7BGMgVP5XGH1ZYv5XGHjhVPNtVSyAVPNhFx1AGP4tVPNtVPNtLPWvoJ1xVvptVSjjZmAoZGf5A20tHPWMLz1gMPVtVP5XGH1goJ1gGH1AVPNtLPWvoJ1gMPptVNbtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVNbtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVNcpZQZmJmR7BGMgDSjjZmAoZGf5A21TDIEOGSASD1jjZmAoZQfjorXNtFpaWlxXPtccozIyBPN9VPtaWlpXKQNmZ1fkBmx2oJ9io29iVT9io28tVPOio29iVT9io29io29io29iVPOio29io29iVPNtKQNmZ1fkBmx3oFOio29io29iomtto29io29io29io28tVT9io29io29iBPNXKQNmZ1fkBmx2oFN4BQttVPN4BQt4olNtBQttVPN4BQttVPNtBQttomt4BPNtVQt4BT8tKQNmZ1fkBmx3oGt4BPNtVPNtVPNtVQt4BPNtVPN4BPOiBQt4VPNtVPN4BPNXKQNmZ1fkBmx2oFN4BQttVPN4BPN4BQuiBQttVPN4BQuio284VPNtBQt4VPNtVPN4BQttVSjjZmAoZGf5A204BQuio29io28tVQt4BT9iomttVPN4BQttVPNtVPNtVPNXKQNmZ1fkBmx2oFN4BQttVPN4BPNtVQt4BQttVPN4BQttVPNtVPNtBQt4olNtVT84BQttVSjjZmAoZGf5A20tVPNtVPNtBQt4VQt4BPNtVPOiolN4BQuiVPNtVPOiolNXKQNmZ1fkBmx2oJ84BQuiVT84BT8tVPNtBQttVT84BQuiVPNtVPNtVPN4BT9iomt4VPNtKQNmZ1fkBmx3oJ84BT9io284BQttomt4BT9iomt4BQttBQt4o29iomt4VPNXVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtPyjjZmAoZGf5Az1NKQNmZ1fkBmx3oHMOIRSZH0IQKQNmZ1fjBmOgPvpaWlxXPzyhMJH5VQ0tXPpaWjbXVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtPyjjZmAoZGf5Az04BPNtBQt4LvNtVPNtVQt4VPN4BQt4BQt4BQt4BPNtYTSxBQt4BTWuYPNtVPNtKQNmZ1fkBmx3oJSxBQt4BQuvLFNtVQt4BQt4BQt4BQt4VPNfLJD4BQt4LzRfVPNtPyjjZmAoZGf5Az04BPNtBQt4BTVtVPNtVQt4VPN4BPNtVPNtVPNtVPOxBPVaVPNtVTNvBTVtVPOpZQZmJmR7BGqgMQtvVPNtVPNvBTVtVQt4VPNtVPNtVPNtVTD4VvptVPNtLPV4LvNtPyjjZmAoZGf5Az04BPNtBQttLQuvVPNtVQt4VPN4BPNtVPNtVPNtVTD4WlNtVPNtVPNtLQuvVPOpZQZmJmR7BGqgJGtfVPNtVPNtVPNtVQt4VPNtVPNtVPNtMQtaVPNtVPNtVPNtVPNtPyjjZmAoZGf5Az04BPNtBQttVTN4LvNtVQt4VPN4BTSuLJSuVPNtVQt4VPNtVPNtVPNtVQt4VPOpZQZmJmR7BGqgLSx4LJSuLJRfVPNtVQt4LJSuLJRtVPNtBQttVPNtVPNtVPNtVPNtPyjjZmAoZGf5Az04BPNtBQttVPOtBTVtVQt4VPN4BPVvVvVvVPNtVQt4VPNtVPNtVPNtVQt4VPOpZQZmJmR7BGqgVPOtVvVvVvV4LvjtVQt4VvVvVvVtVPNtBQttVPNtVPNtVPNtVPNtPyjjZmAoZGf5Az04BPNtBQttVPNtLQuvVQt4VPN4BPNtVPNtVPNtVSx4YPNtVPNtVPNtYQuDVPOpZQZmJmR7BGqgVPNtVPNtVPOtBTVtVQt4VPNtVPNtVPNtJGtfVPNtVPNtVPNtVPNtPyjjZmAoZGf5Az04BPNtBQttVPNtVTN4BQt4VPN4BPNtVPNtVPNtVPOMBTRhVPNtVP5uBSNtVSjjZmAoZGf5A20tJGuuVPNtVPOuBSNtVQt4VPNtVPNtVPNtVSx4LF4tVPNtYzR4HPNtPyjjZmAoZGf5Az04BPNtBQttVPNtVPOtBQt4VPN4BPNtVPNtVPNtVPNtLPWMBQt4BSxvWlNtVSjjZmAoZGf5A20tVPWMBQt4BQuDVvNtVQt4BQt4BQt4BQt4VPOtVyx4BQt4JFVaVPNtPvNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVPNtVNcpZQZmJmR7BGMgDSjjZmAoZGf5A21TDIEOGSASD1jjZmAoZQfjoDbaWlpcPtccozIyZGNtCFNbWlpaPtcpZQZmJmR7BGMgVP8xWPDxWPDtYlDxVPNtYlDxVP8xWPDxWPDxWPNiWPDxWPDxVPNtKQNmZ1fkBmx3oF8xWPDxWPDtVP8xWPDxWPDxWPNtYlDxWPDxWPNXKQNmZ1fkBmx2oKksVPNxWS8isPNxWPDtsPNxWUjtWPEsK19sKl8iWPEsKlNtWPDtKQNmZ1fkBmx3oF8xWS9sVPNxWUjtWPEsK19sKl8tYlDxK18tVPDxPyjjZmAoZGf5Az0tVUjtWPDtVUjtWPDxWUjtWPE8VPDxVPNtVPO8VPDxVPOpVPDxKQNmZ1fkBmx3oKjtWPDtVSksKl98VPDxVPNtVPNtsPNxWPNtKS9sYjcpZQZmJmR7BGMgVPO8VPDxVPO8VPDxVPDxVPDxsPNxWPDxWPNtsPNxWPNtsPNxWSjjZmAoZGf5A218VPNxWPDxWPDtsPNxWPDxWPNtVUjtWPDtVPNtVPNXKQNmZ1fkBmx2oFNtsPNxWPNtsPNxWPNtWPDxWUjtWPEsKl8tVUjtWPDtVUjtWPEpZQZmJmR7BGqgVSksK19sVPNxWUjtWPEsKl8tVPO8VPDxVPNtVPNtPyjjZmAoZGf5Az0tVUjtWPDtVUjtWPEpVPNxWPE8VPDxVPNtVPO8VPDxVPO8VPDxKQNmZ1fkBmx3oFNiWPDtVSjtWPE8VPDxVPNtVPNtsPNxWPNtVPNxWNcpZQZmJmR7BGMgVP8xWPDxWPE8VPDxVSjtVPDxsPNxWPNtVPNtsPNtWPDxWPDxY1jjZmAoZGf5A218VPNxWPDxWPDisPNxWPDxWPDxWUjtVPDxWPDxWP8XKQNmZ1fkBmx2oKksK19sK18isS9sYlNtKS9sY3ksKl8tVPNtVPOpK19sK19sYlOpZQZmJmR7BGqgVSksK19sK18iVUksK19sK19sKl8tKS9sK19sKl8tPtcpZQZmJmR7BGMgDSjjZmAoZGf5A21TDIEOGSASD1jjZmAoZQfjoDbaWlpcPtcfo2qiMz9xLFN9VUWuozEioF5wnT9cL2HbJ2yhMJHkYPOcozIyZvjtnJ5yMGZfVTyhMJH0YPOcozIyAFjtnJ5yMGLfVTyhMJH3YPOcozIyBPjtnJ5yMGxfVTyhMJHkZS0cPzAioaA1oUEuL2IjVQ0tVPtaWlpXKQNmZ1fkBmx2oFNtVS9sK19sVS9sK18tVS8tVPOsVPOsK19sKlOsVPNtVS8tKlNtVS9sK19sK18tVPNtVPNtVPNtVPOpZQZmJmR7BGMgVPOsK19sKlOsK19sK18tK19sK18tVNcpZQZmJmR7BGMgVPNiVS9sK18iVS9sVSk8VSjtsPO8YlOsK19ssPO8VPO8VUjtsPO8K18tVPOsK3jiKPNtVPNtVPNtVSjjZmAoZGf5Az0tYlOsK19ssPNtK19sK3jtVS9sVSjtPyjjZmAoZGf5Az0tsPO8VPNtsPO8VPO8VUjtVSk8VUjtXS9sKlO8VUjtVUjtsPO8VPNtVUjtsPNtYlNtKPNtKQNmZ1fkBmx3oI9sK19sK1jjZmAoZGf5Az18VUjtVPNtsPO8K18tVUjtsS9sXFO8PyjjZmAoZGf5Az0tsPO8VPNtsPO8VPO8VUjtYvOtVUkpK19sVSk8VUjtVUjtsPO8VPNtVUjtsPNiVP9pVSjtKQNmZ1fkBmx3oI9sK19sK1jjZmAoZGf5Az18VUjtVPNtsPNtK198VUjtVS9sKl8tPyjjZmAoZGf5Az0tsPO8K19ssPO8K198VUjtsSjtVUksK19sXFO8VUksK3jtsPO8K19sK3jtsP8tK19sKlOpVPNtVPOpZQZmJmR7BGMgVUjtsS9sK198VUksK19ssPO8VPNtVPNXKQNmZ1fkBmx2oFNtKS9sK19sKS9sK18isS98VSkssS9sK19sYlOpK19sKl98K19sK19ssS8iKl8tVPNtKS9pVPNtVSjjZmAoZGf5Az0tVSksK19sK3ksK19sK198K3jtVPNtPtbtKQNmZ1fkBmx3oHOpZQZmJmR7BGMgEzS0LJkmMJZXWlpaXDcaMKWuoJScoPN9VPtaWlpXKQNmZ1fkBmx2oFOsK19sKlNtK19sK19sK19sK18tVS9sKlOpZQZmJmR7BGqgVPOsK18tVS9sKlNtK19sVPOsK19sKlOsVPNtVPNXKQNmZ1fkBmx2oKjtVS9sVSk8VPOsK198VS9sKlOpYlOsVSjtKQNmZ1fkBmx3oFO8VPOpYlNtsPNiVS8tKUksVPNtK3jtsPNtVPNXKQNmZ1fkBmx2oKjtsPNtKP98VUksKlO8VUksYlNiVP9sKPOpVSjjZmAoZGf5A218VP4tVP4tsP8tY19pVSjtsPO8VUjtsPNtVPNXKQNmZ1fkBmx2oKjtsPOsKlO8VPOsK3k8VPNtVP98VPOsVPO8VSjjZmAoZGf5A218VUkpY3jtsUjtVS8tVUjtsPO8VUjtsPNtVPNXKQNmZ1fkBmx2oKjtsS9pVSk8VUksK198VUkpVSk8VUjtsPO8VSjjZmAoZGf5A218VUjtVUjtsUjtsPO8VUkssPO8K3jtsS9sK18XKQNmZ1fkBmx2oFOpK19sKl9pK19sKl9pK3jtKS9pK3jtsS8iVSjjZmAoZGf5A21pK3jtVUksY1kssPO8Kl9pK19sY1ksK19sKl8XPyjjZmAoZGf5Az1NKQNmZ1fkBmx3oHMuqTSfp2IwKQNmZ1fjBmOgPvpaWlxXnKOcozMiVQ0tXPpaWjcpZQZmJmR7BGMgVPOsK18tK19sKlNtKQNmZ1fkBmx3oI9sKlOsVPNtKlOsK19sKlOsK18tVNcpZQZmJmR7BGMgVUksVS98VPOsVSjtKQNmZ1fkBmx3oI8tK3jtKPO8VUjtVS9sKl8tKlOpVNcpZQZmJmR7BGMgVPO8VUk8VUksXFNtKQNmZ1fkBmx3oKjtsUjtVSk8VUjtsS8tsPO8VUjtsNcpZQZmJmR7BGMgVPO8VUk8VPOsKl8tKQNmZ1fkBmx3oKjtsUjtsSjtVUjtVS98sPO8K3jtsNcpZQZmJmR7BGMgVUksK198K3jtVPOpZQZmJmR7BGqgsS9sK3kssPOpK3kssPNtVSksK18iPtbXKQNmZ1fkBmx3oHOpZQZmJmR7BGMgEzS0LJkmMJApZQZmJmN7ZT0XWlpaXDc0MJkynJ5zolN9VPNbWlpaPyjjZmAoZGf5Az0tVS9sK19sVPNtVS8tVPNtVSjjZmAoZGf5A20tVS9sKlOsVPNtKlOsK19sKlOsK18tVNcpZQZmJmR7BGMgVUksVPNtK3ksK3jtsPOsK19pZQZmJmR7BGqgVUksVS98VSjtsPO8VPOsK18iVS8tKPNXKQNmZ1fkBmx2oFNtVUjtsP8tKlOpVUjiVS8tKPOpZQZmJmR7BGqgsPO8sPNtKUjtsPO8KlO8VUjtsPO8PyjjZmAoZGf5Az0tVPO8VUjtVS9sYlO8VPOsKl8tKQNmZ1fkBmx3oKjtsUjtsSjtVUjtVS98sPO8K3jtsNcpZQZmJmR7BGMgVPNtsS98KS9sK3kssSksK198KQNmZ1fkBmx3oFOsK198K3jtKS98K3jtVPOpK19sYlNXPyjjZmAoZGf5Az1NKQNmZ1fkBmx3oHMuqTSfp2IwPvpaWlxXL29hqTS0olN9VPNbWlpaPyjjZmAoZGf5Az3vybwvybwvybwvybwvybwvybwvyMptVBXJvBXJvBXJvBXJvBXJvBXJvBXIylNt4cnV4cnV4cnV4cnV4cnV4cnV4cJKVBXJvBXJvBXJvBXJvBXJvBXJvBXJvBXJvBXIylOpZQZmJmR7BGqg4cnV4cnV4cnV4cnV4cnV4cnV4cJKVSjjZmAoZGf5Az3vybwvybwvybwvybwvybwvybwvybwvyMpt4cnV4cnV4cnV4cnV4cnV4cJKVBXJvBXJvBXJvBXJvBXJvBXJvBXJvBXJvBXIylQvybwvybwvybwvybwvybwvyMpt4cnV4cnV4cJKVPNtVPQvybwvybwvybwvybwvybwvybwvybwvyMsvybwvybwvybwvybwvybwvybwvybwvyMpt4cnV4cnV4cnV4cnV4cnV4cnV4cJKPyjjZmAoZGf5Az3vybwvybwvyMGvyMQvyMQvybwvybwvyMsvybwvybwvyMGvyMQvyMQvyMQvybwvybwvyMsvybwvybwvyMGvyMQvyMQvyMQvybwvybwvyMsvyMevyMQvyMQvybwvybwvyMGvyMQvyMQvyM1pZQZmJmR7BGqg4cnV4cnV4cJH4cJD4cJD4cJD4cnV4cnV4cJKKQNmZ1fkBmx2orXJvBXJvBXIyBXIxBXIxBXIxBXIxBXIarXJvBXJvBXIyBXIxBXIxBXJvBXJvBXIy+XIzhXIxBXIxBXJvBXJvBXIyBXIxBXIxBXIarXJvBXJvBXIyBXIxBXIxBXJvBXJvBXIy+XJvBXJvBXIxFNtVPNt4cnV4cnV4cJH4cJD4cJD4cJD4cJD4cJq4cnV4cnV4c'
god = 'WU4pWQ4pWQ4pWQ4pWQ4pWd4paI4paI4pWU4pWQ4pWQ4pWQ4pWQ4pWdClwwMzNbMTs5Nm3ilojilojilojilojilojilojilZTilZ3ilojilojilZEgICDilojilojilZHilojilojilZEgICDilojilojilZEgICDilojilojilZEgICBcMDMzWzE7OTdt4paI4paI4pWR4paI4paI4pWX4paI4paI4pWRXDAzM1sxOzk2beKWiOKWiOKWiOKWiOKWiOKVlyAg4paI4paI4paI4paI4paI4paI4paI4pWRICAg4paI4paI4pWRICAg4paI4paI4paI4paI4paI4paI4paI4pWR4paI4paI4pWRICAgICDilojilojilojilojilojilojilojilZfilojilojilojilojilojilZcgIOKWiOKWiOKVkSAgICAgClwwMzNbMTs5Nm3ilojilojilZTilZDilZDilojilojilZfilojilojilZEgICDilojilojilZHilojilojilZEgICDilojilojilZEgICDilojilojilZEgICBcMDMzWzE7OTdt4paI4paI4pWR4paI4paI4pWR4paI4paI4pWRXDAzM1sxOzk2beKWiOKWiOKVlOKVkOKVkOKVnSAg4paI4paI4pWU4pWQ4pWQ4paI4paI4pWRICAg4paI4paI4pWRICAg4paI4paI4pWU4pWQ4pWQ4paI4paI4pWR4paI4paI4pWRICAgICDilZrilZDilZDilZDilZDilojilojilZHilojilojilZTilZDilZDilZ0gIOKWiOKWiOKVkSAgICAgClwwMzNbMTs5Nm3ilojilojilZEgIOKWiOKWiOKVkeKVmuKWiOKWiOKWiOKWiOKWiOKWiOKVlOKVneKVmuKWiOKWiOKWiOKWiOKWiOKWiOKVlOKVnSAgIOKWiOKWiOKVkSAgIFwwMzNbMTs5N23ilZrilojilZHilojilojilojilojilZTilZ1cMDMzWzE7OTZt4paI4paI4pWRICAgICDilojilojilZEgIOKWiOKWiOKVkSAgIOKWiOKWiOKVkSAgIOKWiOKWiOKVkSAg4paI4paI4pWR4paI4paI4paI4paI4paI4paI4paI4pWX4paI4paI4paI4paI4paI4paI4paI4pWR4paI4paI4paI4paI4paI4paI4paI4pWX4pWa4paI4paI4paI4paI4paI4paI4pWXClwwMzNbMTs5Nm3ilZrilZDilZ0gIOKVmuKVkOKVnSDilZrilZDilZDilZDilZDilZDilZ0gIOKVmuKVkOKVkOKVkOKVkOKVkOKVnSAgICDilZrilZDilZ0gICBcMDMzWzE7OTdtIOKVmuKVneKVmuKVkOKVkOKVkOKVnSBcMDMzWzE7OTZt4pWa4pWQ4pWdICAgICDilZrilZDilZ0gIOKVmuKVkOKVnSAgIOKVmuKVkOKVnSAgIOKVmuKVkOKVnSAg4pWa4pWQ4pWd4pWa4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWd4pWa4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWd4pWa4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWdIOKVmuKVkOKVkOKVkOKVkOKVkOKVnQoKCgpcMDMzWzE7OTFtI0NPTlRBVE8jCgpcMDMzWzE7OTZtUFJPVE9OTUFJTDogXDAzM1sxOzk3bXJvb3RmYXRhbHNlY0Bwcm90b25tYWlsLmNoCgpcMDMzWzE7OTZtR0lUSFVCOiBcMDMzWzE7OTdtaHR0cHM6Ly9naXRodWIuY29tL0ZhdGFsUzNDLwoKXDAzM1sxOzk2bVRFTEVHUkFNOiBcMDMzWzE7OTdtaHR0cHM6Ly90Lm1lL2ZhdGFsc2VjClwwMzNbMDswbQonJycpCgpzcWxsb2dvPSAoJycnCgpcMDMzWzE7OTZtIF9fX19fICBfX19fXyBfICAgICAgICAgICAgICAgICAgICAgICAgIApcMDMzWzE7OTZtLyAgX19ffHwgIF8gIHwgfCAgICAgICAgICAgICAgICAgICAgICAgIApcMDMzWzE7OTZtXCBgLS0uIHwgfCB8IHwgfCAgICBcMDMzWzE7OTdtX19fICBfX18gX18gXyBfIF9fICAKXDAzM1sxOzk2bSBgLS0uIFx8IHwgfCB8IHwgICBcMDMzWzE7OTdtLyBfX3wvIF9fLyBfYCB8ICdfIFwgClwwMzNbMTs5Nm0vXF9fLyAvXCBcLycgLyB8X19fXDAzM1sxOzk3bVxfXyBcIChffCAoX3wgfCB8IHwgfApcMDMzWzE7OTZtXF9fX18vICBcXy9cX1xfX19fX1wwMzNbMTs5N20vX19fL1xfX19cX18sX3xffCB8X3wKClwwMzNbMTs5Nm1AXDAzM1sxOzk3bUZhdGFsc2VjCicnJykKCndob2lzbG9nbyA9ICgnJycKXDAzM1sxOzk2bSBfICAgICAgIF9fX18gICAgICAgICBcMDMzWzE7OTdtIF8gICAgIApcMDMzWzE7OTZtfCB8ICAgICAvIC8gL18gIF9fX18gXDAzM1sxOzk3bSAoXylfX19fClwwMzNbMTs5Nm18IHwgL3wgLyAvIF9fIFwvIF9fIFwgXDAzM1sxOzk3bS8gLyBfX18vClwwMzNbMTs5Nm18IHwvIHwvIC8gLyAvIC8gL18vIC9cMDMzWzE7OTdtIChfXyAgKSAKXDAzM1sxOzk2bXxfXy98X18vXy8gL18vXF9fX18vXDAzM1sxOzk3bV8vX19fXy8gIAoKXDAzM1sxOzk2bUBcMDMzWzE7OTdtRmF0YWxzZWMgICAgICAgICAgICAgICAgICAgICAgICAgIAonJycpCm5tYXBsb2dvID0gKCcnJwpcMDMzWzE7OTZtICAgICBfXyAgICAgICAgICAgICAgICAgICAgICAgClwwMzNbMTs5Nm0gIC9cIFwgXCAKXDAzM1sxOzk2bSAvICBcLyAvIFwwMzNbMTs5N20nXyBgIF8gXCAvIF9gIHwgJ18gXCAKXDAzM1sxOzk2bS8gL1wgIC9cMDMzWzE7OTdtfCB8IHwgfCB8IHwgKF98IHwgfF8pIHwKXDAzM1sxOzk2bVxfXCBcLyBcMDMzWzE7OTdtfF98IHxffCB8X3xcX18sX3wgLl9fLyAKXDAzM1sxOzk2bSAgICAgIFwwMzNbMTs5N20gICAgICAgICAgICAgICAgIHxffCAgICAKClwwMzNbMTs5Nm0gQFwwMzNbMTs5N21GYXRhbHNlY1wwMzNbMDswbQonJycpCgoKcHJpbnQgKGxvZ29mb2RhKQpwcmludCAodmVyKQp0cnk6Cgl0aW1lLnNsZWVwKDEpCmV4Y2VwdCBLZXlib2FyZEludGVycnVwdDoKICAgIHByaW50ICgnICcpCiAgICBwcmludCAoJ1wwMzNbMTs5Nm1TQ1JJUFQgXDAzM1sxOzkxbUNBTkNFTEFETyEgXDAzM1swOzBtJykKICAgIGV4aXQoMCkKYSA9IHVybGxpYi5yZXF1ZXN0LnVybG9wZW4oImh0dHBzOi8vZ2VuZXJhdG9yLmVtYWlsLyIpLmdldGNvZGUoKQoKcHJpbnQgKCcnJwoKXDAzM1sxOzk2bVtcMDMzWzE7OTdtMVwwMzNbMTs5Nm1dIFwwMzNbMTs5N21JTlNUQUxBUiBSRVFVSVNJVE9TCgpcMDMzWzE7OTZtW1wwMzNbMTs5N20yXDAzM1sxOzk2bV0gXDAzM1sxOzk3bVdIT0lTCgpcMDMzWzE7OTZtW1wwMzNbMTs5N20zXDAzM1sxOzk2bV0gXDAzM1sxOzk3bU5NQVAKClwwMzNbMTs5Nm1bXDAzM1sxOzk3bTRcMDMzWzE7OTZtXSBcMDMzWzE7OTdtU1FMLUlpbmplY3Rpb24tU2Nhbm5lcgoKXDAzM1sxOzk2bVtcMDMzWzE7OTdtNVwwMzNbMTs5Nm1dIFwwMzNbMTs5N21UZWxlSU5GTwoKXDAzM1sxOzk2bVtcMDMzWzE7OTdtNlwwMzNbMTs5Nm1dIFwwMzNbMTs5N21JUElORk8KClwwMzNbMTs5Nm1bXDAzM1sxOzk3bTdcMDMzWzE7OTZtXSBcMDMzWzE7OTdtR2VyYWRvciBkZSBlbWFpbAoKXDAzM1sxOzk2bVtcMDMzWzE7OTdtOFwwMzNbMTs5Nm1dIFwwMzNbMTs5N21Db25zdWx0YSBDRVAKClwwMzNbMTs5Nm1bXDAzM1sxOzk3bTlcMDMzWzE7OTZtXSBcMDMzWzE7OTdtQ29uc3VsdGEgTUFDCgpcMDMzWzE7OTZtW1wwMzNbMTs5N20xMFwwMzNbMTs5Nm1dIFwwMzNbMTs5N21Db250YXRvCicnJykKCnRyeToKCWZlcnJhbWVudGEgPSBpbnQoaW5wdXQoIlwwMzNbMTs5Nm1Fc2NvbGhhOiBcMDMzWzE7OTdtIikpCgoJaWYgZmVycmFtZW50YSA9PSAxOgoJCWltcG9ydCBvcwoJCWltcG9ydCB0aW1lCgkJb3Muc3lzdGVtKCdwaXAzIGluc3RhbGwgLXIgcmVxdWlyZW1lbnRzLnR4dCcpCgkJZnJvbSBwcm9ncmVzcy5iYXIgaW1wb3J0IENoYXJnaW5nQmFyCgkJYmFyID0gQ2hhcmdpbmdCYXIoJ1wwMzNbMTs5Nm1JbnN0YWxhbmRvIHJlcXVpc2l0b3MuLi4gXDAzM1sxOzk3bScsIG1heD0xMCkKCQlvcy5zeXN0ZW0oJ2NsZWFyJykKCQlmb3IgaSBpbiByYW5nZSgxMCk6CgkJICAgIHRpbWUuc2xlZXAoMC41KQoJCSAgICBiYXIubmV4dCgpCgkJYmFyLmZpbmlzaCgpCgkJcHJpbnQgKCdcMDMzWzE7OTJtSU5TVEFMQURPIVwwMzNbMDswbScpCgoKCWlmIGZlcnJhbWVudGEgPT0gMjoKCQlpbXBvcnQgd2hvaXMKCQlpbXBvcnQgb3MKCQlpbXBvcnQgc29ja2V0CgkJb3Muc3lzdGVtKCdjbGVhcicpCgkJcHJpbnQgKHdob2lzbG9nbykKCQlhbHZvID0gaW5wdXQoIlwwMzNbMTs5Nm1TaXRlIGFsdm8vaXA6IFwwMzNbMTs5N20iKQoJCWlwID0gc29ja2V0LmdldGhvc3RieW5hbWUoYWx2bykKCQlkb21haW4gPSB3aG9pcy53aG9pcyhhbHZvKQoJCXByaW50IChmIiIiCgpcMDMzWzE7OTFtI0lORk9STUHDh8OVRVMgQsOBU0lDQVMjCgpcMDMzWzE7OTZtSVA6IFwwMzNbMTs5N217aXB9CgpcMDMzWzE7OTZtTm9tZSBEbyBEb21pbmlvOiBcMDMzWzE7OTdte2RvbWFpbi5uYW1lfQoKXDAzM1sxOzk2bURhdGEgRGUgQXR1YWxpemHDp8OjbzogXDAzM1sxOzk3bXtkb21haW4udXBkYXRlZF9kYXRlfQoKXDAzM1sxOzk2bURhdGEgRGUgQ3JpYcOnw6NvOiBcMDMzWzE7OTdte2RvbWFpbi5jcmVhdGlvbl9kYXRlfQoKXDAzM1sxOzk2bURhdGEgRGUgRXhwaXJhw6fDo286IFwwMzNbMTs5N217ZG9tYWluLmV4cGlyYXRpb25fZGF0ZX0KClwwMzNbMTs5Nm1FbWFpbHM6IFwwMzNbMTs5N217ZG9tYWluLmVtYWlsc30KCgpcMDMzWzE7OTFtI0dFTyMKClwwMzNbMTs5Nm1Pcmc6IFwwMzNbMTs5N217ZG9tYWluLm9yZ30KClwwMzNbMTs5Nm1FbmRlcmXDp286IFwwMzNbMTs5N217ZG9tYWluLmFkZHJlc3N9CgpcMDMzWzE7OTZtQ2lkYWRlOiBcMDMzWzE7OTdte2RvbWFpbi5jaXR5fQoKXDAzM1sxOzk2bUVzdGFkbzogXDAzM1sxOzk3bXtkb21haW4uc3RhdGV9CgpcMDMzWzE7OTZtQ8OzZGlnbyBwb3N0YWw6IFwwMzNbMTs5N217ZG9tYWluLnN0YXRlfQoKXDAzM1sxOzk2bVBhw61zOiBcMDMzWzE7OTdte2RvbWFpbi5jb3VudHJ5fQoKCgpcMDMzWzE7OTFtI1NFUlZJRE9SRVMjCgpcMDMzWzE7OTZtU3RhdHVzOiBcMDMzWzE7OTdte2RvbWFpbi5zdGF0dXN9CgoKXDAzM1sxOzk2bU5vbWUgZG9zIHNlcnZpZG9yZXM6IFwwMzNbMTs5N217ZG9tYWluLm5hbWVfc2VydmVyc30KCQkiIiIpCglpZiBmZXJyYW1lbnRhID09IDM6CgkJaW1wb3J0IG5tYXAzCgkJaW1wb3J0IG9zCgkJb3Muc3lzdGVtKCdjbGVhcicpCgkJcHJpbnQgKG5tYXBsb2dvKQoJCW5tYXAgPSBubWFwMy5ObWFwKCkKCQluID0gbm1hcDMuTm1hcFNjYW5UZWNobmlxdWVzKCkKCQlpbXBvcnQgdGltZQoJCWFsdm8gPSBpbnB1dCgiXDAzM1sxOzk2bVNpdGUgYWx2bzogXDAzM1sxOzk3bSIpCgkJcHJpbnQgKCIiIgpcMDMzWzE7OTZtMVwwMzNbMTs5N21dIFwwMzNbMTs5N21UT1AgUE9SVFMKClwwMzNbMTs5Nm0yXDAzM1sxOzk3bV0gXDAzM1sxOzk3bUROUyBCUlVURQoKXDAzM1sxOzk2bTNcMDMzWzE7OTdtXSBcMDMzWzE7OTdtT1MgSU5ERU5USUZZCgpcMDMzWzE7OTZtNFwwMzNbMTs5N21dIFwwMzNbMTs5N21WRVJTw4NPCgpcMDMzWzE7OTZtNVwwMzNbMTs5N21dIFwwMzNbMTs5N21MSVNUIFNDQU4KClwwMzNbMTs5Nm02XDAzM1sxOzk3bV0gXDAzM1sxOzk3bVNVQk5FVCBTQ0FOCgoKXDAzM1sxOzkxbSNURUNOSUNBUyBERSBTQ0FOIwoKClwwMzNbMTs5Nm03XDAzM1sxOzk3bV0gXDAzM1sxOzk3bUZJTiBTQ0FOCgpcMDMzWzE7OTZtOFwwMzNbMTs5N21dIFwwMzNbMTs5N21JRExFIFNDQU4KClwwMzNbMTs5Nm05XDAzM1sxOzk3bV0gXDAzM1sxOzk3bVBJTkcgU0NBTgoKXDAzM1sxOzk2bTEwXDAzM1sxOzk3bV0gXDAzM1sxOzk3bVNZTiBTQ0FOCgpcMDMzWzE7OTZtMTFcMDMzWzE7OTdtXSBcMDMzWzE7OTdtVENQIFNDQU4KClwwMzNbMTs5Nm0xMlwwMzNbMTs5N21dIFwwMzNbMTs5N21VRFAgU0NBTgoKCgkJIiIiKQoJCXNjYW4gPSBpbnQoaW5wdXQoIlwwMzNbMTs5Nm1Fc2NvbGhhIHVtYSBvcMOnw6NvOiBcMDMzWzE7OTdtIikpCgoKCQoJCWlmIHNjYW4gPT0gMToKCQkJZmRzID0gbm1hcC5zY2FuX3RvcF9wb3J0cyhhbHZvKQoJCQlwcmludCAoZmRzKQoJCQkKCQlpZiBzY2FuID09IDI6CgkJCWZkcyA9IG5tYXAubm1hcF9kbnNfYnJ1dGVfc2NyaXB0KGFsdm8pCgkJCXByaW50IChmZHMpCgkKCQlpZiBzY2FuID09IDM6CgkJCWZkcyA9IG5tYXAubm1hcF9vc19kZXRlY3Rpb24oYWx2bykKCQkJcHJpbnQgKGZkcykKCQoJCWlmIHNjYW4gPT0gNDoKCQkJZmRzID0gbm1hcC5ubWFwX3ZlcnNpb25fZGV0ZWN0aW9uKGFsdm8pC'
destiny = 'txWPKOlnJ50VPuzMUZcPtxXPDycMvOmL2ShVQ09VQH6PtxWPJMxplN9VT5gLKNhoz1upS9fnKA0K3AwLJ4bLJk2olxXPDxWpUWcoaDtXTMxplxXPDxXPDycMvOmL2ShVQ09VQL6PtxWPJMxplN9VT5gLKNhoz1upS9mqJWhMKEsp2AuovuuoUMiXDbWPDyjpzyhqPNbMzEmXDbWPtxWnJLtp2AuovN9CFN3BtbWPDyzMUZlVQ0tov5hoJSjK2Mcoy9mL2ShXTSfqz8cPtxWPKOlnJ50VPuzMUZlXDbXPDycMvOmL2ShVQ09VQt6PtxWPJMxpmVtCFOhYz5gLKOsnJEfMI9mL2ShXTSfqz8cPtxWPKOlnJ50VPuzMUZlXDxXPDycMvOmL2ShVQ09VQx6PtxWPJMxpmVtCFOhYz5gLKOspTyhM19mL2ShXTSfqz8cPtxWPKOlnJ50VPuzMUZlXDbWPtxWnJLtp2AuovN9CFNkZQbXPDxWMzEmZvN9VT4hoz1upS9mrJ5sp2AuovuuoUMiXDbWPDyjpzyhqPNbMzEmZvxXPDxXPDycMvOmL2ShVQ09VQRkBtbWPDyzMUZlVQ0tov5hoJSjK3EwpS9mL2ShXTSfqz8cPtxWPKOlnJ50VPuzMUZlXDbWPDbWPJyzVUAwLJ4tCG0tZGV6PtxWPJMxpmVtCFOhYz5gLKOsqJEjK3AwLJ4bLJk2olxXPDxWpUWcoaDtXTMxpmVcPtxWPtycMvOzMKWlLJ1yoaEuVQ09VQD6PtxWnJ1jo3W0VUWypKIyp3EmPtxWMaWioFOvpmDtnJ1jo3W0VRWyLKI0nJM1oSAiqKNXPDycoKOipaDtpzHXPDycoKOipaDtMTS0MKEcoJHXPDycoKOipaDtqTygMDbWPJS0qJSfVQ0tMTS0MKEcoJHhMTS0MKEcoJHhoz93XPxXPDyjpzyhqPNbVyjjZmAoZGf5Az1fMJ1vpzHgp2HtMTHtMTyanKEupvOiVTIhMTIlMpBaolOwo20tolNtnUE0pUZto3HtnUE0pPRvXDbWPKAcqTHtCFOcoaO1qPtvKQNmZ1fkBmx2oHIhMTIlMpBaombtKQNmZ1fkBmx3oFVcPtxWpTSaMFN9VUWypKIyp3EmYzqyqPumnKEyXDbWPKAiqKNtCFOPMJS1qTyzqJkGo3IjXUOuM2HhqTI4qPjtW2u0oJjhpTSlp2IlWlxXPDycozMipz1uL2SiVQ0tXTLaWlpXKQNmZ1fkBmx2oIAQDH4tKQNmZ1fkBmx3oHyBFHAWDHECPtcpZQZmJmR7BGMgDHkJGmbtKQNmZ1fkBmx3oKgmnKEysDbXPyjjZmAoZGf5Az1RDIEOBvOpZQZmJmR7BGqgr2S0qJSfYzEurK1pZQZmJmR7BGMgY1jjZmAoZGf5A21pZQZmJmR7BGqgr2S0qJSfYz1ioaEbsIjjZmAoZGf5Az0iKQNmZ1fkBmx3oIjjZmAoZGf5A217LKE1LJjhrJIupa1pZQZmJmR7BGMgPtbXKQNmZ1fkBmx2oHuCHxR6VSjjZmAoZGf5A217LKE1LJjhnT91pa1pZQZmJmR7BGMgByjjZmAoZGf5A217LKE1LJjhoJyhqKEysIjjZmAoZGf5Az06KQNmZ1fkBmx3oKguqUIuoP5mMJAiozE9KQNmZ1fkBmx2oDbWPFpaWlxXPDbWPJyzVUWyYaAyLKWwnPtaH3SfWljtp291pP50MKu0XGbXPDxWpUWcoaDtXPqpZQZmJmR7BGMgH2y0MFO2qJkhMKWuqzIfVTRtKQNmZ1fkBmxkoIAEGRyBFxIQIRyCGvSpZQZmJmN7ZT0aXDbWPDyjpzyhqPNbnJ5zo3WgLJAuolxXPDxXPDyyoUAyBtbWPDy0nJ1yYaAfMJIjXQVcPtxWPKOlnJ50VPtaGzIhnUIgVTIlpz8tMJ5wo250pzSxoljtqTIhqTShMT8toz92LJ1yoaEyWlxXPDxWnJLtpzHhp2IupzAbXPqGHHjaYPOmo3IjYaEyrUDcBtbWPDxWpUWcoaDtXPqpZQZmJmR7BGMgH2y0MFO2qJkhMKWuqzIfVTRtKQNmZ1fkBmxkoIAEGRyBFxIQIRyCGvSpZQZmJmN7ZT0aXDbWPDxWpUWcoaDtXTyhMz9loJSwLJ8cPtxWPJIfp2H6PDbWPDxWqTygMF5moTIypPtlXDbWPDxWpUWcoaDtXPqBMJ5bqJ0tMKWlolOyozAioaElLJEiYPO0MJ50LJ5xolOho3MuoJIhqTHaXDbWPDxWnJLtpzHhp2IupzAbXPqmpJjaYPOmo3IjYaEyrUDcBtbWPDxWPKOlnJ50VPtaKQNmZ1fkBmx2oIAcqTHtqaIfozIlLKMyoPOuVSjjZmAoZGf5ZJ1GHHkWGxcSD1EWG04uKQNmZ1fjBmOgWlxXPDxWPDyjpzyhqPNbnJ5zo3WgLJAuolxXPtycMvOzMKWlLJ1yoaEuVQ09VQH6PtxWnJ1jo3W0VUObo25yoaIgLzIlpjbWPJygpT9lqPOipjbWPJMlo20tpTuiozIhqJ1vMKWmVTygpT9lqPOaMJ9wo2EyptbWPJMlo20tpTuiozIhqJ1vMKWmVTygpT9lqPOwLKWlnJIlPtxWMaWioFOjnT9hMJ51oJWypaZtnJ1jo3W0VUEcoJI6o25yPtxWo3Zhp3ymqTIgXPqwoTIupvpcPtxWpUWcoaDtXUEyoTIcozMiXDbWPKEyoTIzo25yVQ0tnJ5jqKDbVyjjZmAoZGf5Az1HMJkyMz9hMGbtKQNmZ1fkBmx3oFVcPtxWL2IfoPN9VUObo25yoaIgLzIlpl5jLKWmMFtvXlVtXlO0MJkyMz9hMFxXPDywnJEuMTHtCFNbM2IiL29xMKVhMTImL3WcpUEco25sMz9lK251oJWypvuwMJkfYPNaMJ4aXFxXPDyxLKEuMz9xLFN9VPu0nJ1yrz9hMF50nJ1yK3ciozImK2Mipy9hqJ1vMKVbL2IfoPxcPtxWo3OypzSxo3WuVQ0tVPuwLKWlnJIlYz5uoJIsMz9lK251oJWypvuwMJkfYPNvMJ4vXFxXPtxWpUWcoaDtXTLaWlpXKQNmZ1fkBmxkoFAWGxMCVjbXKQNmZ1fkBmx2oIESGRITG05SBvOpZQZmJmR7BGqgr2AyoTk9PtcpZQZmJmR7BGMgEIAHDHECBvOpZQZmJmR7BGqgr2AcMTSxMK0XPyjjZmAoZGf5Az1HFH1SJx9BEGbtKQNmZ1fkBmx3oKgxLKEuMz9xLK0XPyjjZmAoZGf5Az1CHRIFDHECHxR6VSjjZmAoZGf5A217o3OypzSxo3WusDbXKQNmZ1fkBmxkoFAWGxMCVjbWPFpaWlxXPtycMvOzMKWlLJ1yoaEuVQ09VQL6PtxWnJ1jo3W0VT9mPtxWo3Zhp3ymqTIgXPqwoTIupvpcPtxWpUWcoaDtXTyjnJ5zolxXPDycoKOipaDtnKOcozMiPtxWLJAwMKAmK3Ein2IhVQ0tWmZ2L2ZjZJH5ZQMyAQNkWjbWPJuuozEfMKVtCFOcpTyhMz8hM2I0FTShMTkypvuuL2Ayp3AsqT9eMJ4cPtbWPJyjVQ0tnJ5jqKDbVyjjZmAoZGf5Az1SozEypzKQc28tFIN6VSjjZmAoZGf5A20vXDbWPJMiMTRtCFObLJ5xoTIlYzqyqREyqTScoUZbnKNcPtxWpUWcoaDtXTLaWlpXPDcpZQZmJmR7BGMgFIN6VSjjZmAoZGf5A217nKO9PtcpZQZmJmR7BGMgD0yRDHESBvOpZQZmJmR7BGqgr2MiMTRhL2y0rK0XPyjjZmAoZGf5Az1FEHqWj4ACBvOpZQZmJmR7BGqgr2MiMTRhpzIanJ9hsDbXKQNmZ1fkBmx2oHkCD0SZFIcOj4sQt086VSjjZmAoZGf5A217Mz9xLF5fo2A9PtcpZQZmJmR7BGMgG1WUBvOpZQZmJmR7BGqgr2MiMTRho3WasDbXKQNmZ1fkBmx2oIOCH1EOGQbtKQNmZ1fkBmx3oKgzo2EuYaOip3EuoU0XPyjjZmAoZGf5Az1HFH1SJx9BEGbtKQNmZ1fkBmx3oKgzo2EuYaEcoJI6o25ysDbWPFpaWlxXPtycMvOzMKWlLJ1yoaEuVQ09VQp6PtxWnJ1jo3W0VT9mPtxWo3Zhp3ymqTIgXPqwoTIupvpcPtxWpUWcoaDtXTqypzSgLJyfXDbWPJRtCFO1pzkfnJVhpzIkqJImqP51pzkipTIhXPWbqUEjpmbiY2qyozIlLKEipv5yoJScoP8vXF5aMKEwo2EyXPxXPDycMvOuVQ09VQVjZQbXPDxWpUWcoaDtXPqpZQZmJmR7BGMgH0IFIxyRG1VtKQNmZ1fkBmxloH9BGRyBEIjjZmAoZQfjoFpcPtxWPJMlo20tLaZ0VTygpT9lqPOPMJS1qTyzqJkGo3IjPtxWPJygpT9lqPOlMKS1MKA0pjbWPDyjLJqyVQ0tpzIkqJImqUZhM2I0XPqbqUEjpmbiY2qyozIlLKEipv5yoJScoP8aXDbWPDymo3IjVQ0tDzIuqKEcMaIfH291pPujLJqyYaEyrUDfVPqbqT1fYaOupaAypvpcPtxWPJIgLJyfVQ0tp291pP5znJ5xXTyxCFWyoJScoS9wnS90MKu0VvxXPDxWpUWcoaDtXTLaWlpXPyjjZmAoZGf5Az1SGHSWGQbtKQNmZ1fkBmx3oKgyoJScoP50MKu0sDbXKQNmZ1fkBmx2oHkWGxftERHtDHASH1ACBvOpZQZmJmR7BGqgnUE0pUZ6Yl9aMJ5ypzS0o3VhMJ1unJjir2IgLJyfYaEyrUE9PtbWPDxaWlpcPtxWMJkmMGbXPDxWpUWcoaDtXPqpZQZmJmR7BGMgH0IFIxyRG1VtKQNmZ1fkBmxkoH9TExkWGxIpZQZmJmN7ZT0aXDbWPDyyrTy0XQNcPtxWPtycMvOzMKWlLJ1yoaEuVQ09VQt6PtxWnJ1jo3W0VUIloTkcLv5lMKS1MKA0PtxWnJ1jo3W0VT9mPtxWLFN9VUIloTkcLv5lMKS1MKA0YaIloT9jMJ4bVzu0qUOmBv8iqzyuL2IjYzAioF5vpvVcYzqyqTAiMTHbXDbWPJAioaA1oUEuL2IjVQ0tVPtaWlpXKQNmZ1fkBmx2oFNtVS9sK19sVS9sK18tVS8tVPOsVPOsK19sKlOsVPNtVS8tKlNtVS9sK19sK18tVPNtVPNtVPNtVPOpZQZmJmR7BGMgVPOsK19sKlOsK19sK18tK19sK18tVNcpZQZmJmR7BGMgVPNiVS9sK18iVS9sVSk8VSjtsPO8YlOsK19ssPO8VPO8VUjtsPO8K18tVPOsK3jiKPNtVPNtVPNtVSjjZmAoZGf5Az0tYlOsK19ssPNtK19sK3jtVS9sVSjtPyjjZmAoZGf5Az0tsPO8VPNtsPO8VPO8VUjtVSk8VUjtXS9sKlO8VUjtVUjtsPO8VPNtVUjtsPNtYlNtKPNtKQNmZ1fkBmx3oI9sK19sK1jjZmAoZGf5Az18VUjtVPNtsPO8K18tVUjtsS9sXFO8PyjjZmAoZGf5Az0tsPO8VPNtsPO8VPO8VUjtYvOtVUkpK19sVSk8VUjtVUjtsPO8VPNtVUjtsPNiVP9pVSjtKQNmZ1fkBmx3oI9sK19sK1jjZmAoZGf5Az18VUjtVPNtsPNtK198VUjtVS9sKl8tPyjjZmAoZGf5Az0tsPO8K19ssPO8K198VUjtsSjtVUksK19sXFO8VUksK3jtsPO8K19sK3jtsP8tK19sKlOpVPNtVPOpZQZmJmR7BGMgVUjtsS9sK198VUksK19ssPO8VPNtVPNXKQNmZ1fkBmx2oFNtKS9sK19sKS9sK18isS98VSkssS9sK19sYlOpK19sKl98K19sK19ssS8iKl8tVPNtKS9pVPNtVSjjZmAoZGf5Az0tVSksK19sK3ksK19sK198K3jtVPNtPtbtKQNmZ1fkBmx3oHOpZQZmJmR7BGMgEzS0LJkmMJZXPDxaWlpcPtxWnJLtLFN9CFNlZQN6PtxXPDxWpUWcoaDtXPqpZQZmJmR7BGMgH0IFIxyRG1VtKQNmZ1fkBmxloH9BGRyBEIjjZmAoZQfjoFpcPtxWPJ9mYaA5p3EyoFtaL2kyLKVaXDbWPDyjpzyhqPNbL29hp3IfqTSwMKNcPtxWPJMlo20tLaZ0VTygpT9lqPOPMJS1qTyzqJkGo3IjPtxWPJygpT9lqPOlMKS1MKA0pjbWPDywMKNtCFOcoaO1qPtvKQNmZ1fkBmx2oHASHQbtKQNmZ1fkBmx3oFVcPtxWPJ9mYaA5p3EyoFtaL2kyLKVaXDbWPDyjLJqyVQ0tpzIkqJImqUZhM2I0XTLanUE0pUZ6Yl92nJSwMKNhL29gYzWlY3qmY3gwMKO9Y3ugoP8aXDbWPDymo3IjVQ0tDzIuqKEcMaIfH291pPujLJqyYaEyrUDfVPqbqT1fYaOupaAypvpcPtxWPKOlnJ50VPuzWlpaPtxXKQNmZ1fkBmx2oHASHQbtKQNmZ1fkBmx3oKgmo3IjYzMcozDbW2AypPpcYaEyrUE9PtcpZQZmJmR7BGMgGR9UHxSRG1IFGmbtKQNmZ1fkBmx3oKgmo3IjYzMcozDbW2kiM3WuMT91pz8aXF50MKu0sDbXKQNmZ1fkBmx2oHWOFIWFGmbtKQNmZ1fkBmx3oKgmo3IjYzMcozDbW2WunKWlolpcYaEyrUE9PtcpZQZmJmR7BGMgGR9QDHkWERSREGbtKQNmZ1fkBmx3oKgmo3IjYzMcozDbW2kiL2SfnJEuMTHaXF50MKu0sDbXKQNmZ1fkBmx2oHIGIRSRGmbtKQNmZ1fkBmx3oKgmo3IjYzMcozDbW3IzWlxhqTI4qU0XPyjjZmAoZGf5Az1WDxqSBvOpZQZmJmR7BGqgr3AiqKNhMzyhMPtanJWaMFpcYaEyrUE9PtcpZQZmJmR7BGMgERERBvOpZQZmJmR7BGqgr3AiqKNhMzyhMPtaMTExWlxhqTI4qU0XPyjjZmAoZGf5Az1GFHSTFGbtKQNmZ1fkBmx3oKgmo3IjYzMcozDbW3AcLJMcWlxhqTI4qU0XPDxWWlpaXDbWPJIfp2H6PtxWPKOlnJ50VPtaKQNmZ1fkBmx2oIASHyMWER9FVSjjZmAoZGf5ZJ1CExMZFH5SKQNmZ1fjBmOgWlxXPDxWMKucqPtjXDbXPtbXPtycMvOzMKWlLJ1yoaEuVQ09VQRjBtbWPKOlnJ50VPuwo250LKEiXDbWPDbWnJLtMzIlpzSgMJ50LFN9CFN5BtbWPJygpT9lqPOipjbWPJMlo20tLaZ0VTygpT9lqPOPMJS1qTyzqJkGo3IjPtxWnJ1jo3W0VUWypKIyp3EmPtxWo3Zhp3ymqTIgXPqwoTIupvpcPtxWpUWcoaDtXTAioaA1oUEuoJSwXDbWPJ1uLlN9VTyhpUI0XPWpZQZmJmR7BGMgGHSQBvOpZQZmJmR7BGqgVvxXPDyjLJqyVQ0tpzIkqJImqUZhM2I0XTLanUE0pUZ6Yl9upTxhoJSwqzIhMT9lpl5wo20ir21uL30aXDbWPJ1uL3ZtCFOPMJS1qTyzqJkGo3IjXUOuM2HhqTI4qPjtW2u0oJjhpTSlp2IlWlxXPDyjpzyhqPNbMvqpZQZmJmR7BGMgFH5TGmbtKQNmZ1fkBmx3oKggLJAmsFOpZQZmJmN7ZT0aXDbWPJI4nKDbXDcyrTAypUDtF2I5Lz9upzEWoaEypaW1pUD6PvNtVPOjpzyhqPNbWlNaXDbtVPNtpUWcoaDtXPqpZQZmJmR7BGMgH0AFFIOHVSjjZmAoZGf5ZJ1QDH5QEHkOER8uVSjjZmAoZQfjoFpcPt=='
joy = '\x72\x6f\x74\x31\x33'
trust = eval('\x6d\x61\x67\x69\x63') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x6c\x6f\x76\x65\x2c\x20\x6a\x6f\x79\x29') + eval('\x67\x6f\x64') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x64\x65\x73\x74\x69\x6e\x79\x2c\x20\x6a\x6f\x79\x29')
eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
